import type { Strings } from './ka'

export const en: Strings = {
  nav: {
    brands: 'Brands',
    creators: 'Creators',
    howItWorks: 'How it works',
    faq: 'FAQ',
    signIn: 'Sign in',
    signUp: 'Sign up',
    dashboard: 'Dashboard',
  },
  footer: {
    tagline: 'Georgian affiliate platform for creators and merchants.',
    platform: 'Platform',
    forCreators: 'For Creators',
    forMerchants: 'For Merchants',
    copyright: 'Built for creators',
    about: 'About',
    howItWorks: 'How it works',
    faq: 'FAQ',
    contact: 'Contact',
    signUp: 'Sign up',
    merchants: 'Merchants',
    creatorDashboard: 'Creator dashboard',
    joinAsMerchant: 'Join as merchant',
    merchantDashboard: 'Merchant dashboard',
    poweredBy: 'powered by',
  },
  landing: {
    badge: 'Online store + affiliate marketing, together',
    headline1: 'Sell more.',
    headline2: 'Work less.',
    tagline: 'Your store, inventory tracking, AI chat agent, and creator network — all on one platform.',
    ctaSignUp: 'Get started free',
    ctaHowItWorks: 'How it works',
    heroChatQuestion: 'Is it available in size 42?',
    heroChatAnswer: 'Yes, in stock ✅',
    heroCreatorsSelling: '3 creators selling',
    heroCommissionLabel: 'commission',
    heroAddToCart: '+ Cart',
    featuredBrandsLabel: '✦ Featured brands',
    partnerShops: 'Partner shops',
    viewAll: 'View all',
    merchantsBadge: 'For merchants',
    merchantsTitle: 'Everything your store needs',
    merchantsAccent: 'in one platform.',
    merchantFeature1Title: 'Online store',
    merchantFeature1Body: 'Launch a branded storefront in minutes — design, categories, pages, all yours to control.',
    merchantFeature2Title: 'Inventory tracking',
    merchantFeature2Body: 'Track stock down to the variant — size, color, whatever you sell. Never oversell again.',
    merchantFeature3Title: 'Facebook & Instagram',
    merchantFeature3Body: 'Import products straight from your posts, or publish to both platforms in one click.',
    merchantFeature4Title: 'AI messaging agent',
    merchantFeature4Body: 'An AI agent replies to customers on Messenger automatically — checks stock, answers questions, and drafts orders for you to confirm.',
    merchantFeature5Title: 'Affiliate marketing',
    merchantFeature5Body: 'Let creators sell your products to their own audience — you only pay when it results in a sale.',
    howItWorksBadge: 'For creators',
    howItWorksTitle: 'Three steps',
    howItWorksAccent: 'to your first commission.',
    step1Title: 'Register',
    step1Body: 'Open a free account in seconds. No card required.',
    step2Title: 'Get your link',
    step2Body: 'Get a unique promo code or tracking link for any partner merchant.',
    step3Title: 'Earn',
    step3Body: 'Every sale earns commission. Track your revenue in real time.',
    ctaTitle: 'Ready to\nget started?',
    ctaBody: 'Whether you want to build a store or earn as a creator — join NipNip today.',
    ctaFree: 'Sign up for free',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    loading: 'Loading…',
    submitting: 'Submitting…',
    error: 'An error occurred. Please try again.',
    clear: 'Clear',
    copy: 'Copy',
    copied: 'Copied!',
    prev: 'Previous',
    next: 'Next',
    records: 'records',
    total: 'Total',
  },
  sidebar: {
    creatorBadge: 'Creator',
    merchantBadge: 'Merchant',
    dashboard: 'Dashboard',
    myLinks: 'My Links',
    earnings: 'Earnings',
    payouts: 'Payouts',
    conversions: 'Conversions',
    reportSale: 'Report Sale',
    store: 'Store',
    settings: 'Settings',
    browseMarketplace: 'Browse Merchants',
    marketplace: 'Marketplace',
    integration: 'Integration',
    affiliateGroup: 'Affiliate Marketing',
    onlineStoreGroup: 'Online Store',
    aiAgentsGroup: 'AI Agents',
    messagingAgent: 'Messaging Agent',
    storeOverview: 'Details',
    storeOrders: 'Orders',
    storeCategories: 'Categories',
    storePages: 'Pages',
    storeDesign: 'Design',
    storeProducts: 'Products',
    storeMessages: 'Messages',
    storeContact: 'Contact & Socials',
    storePayments: 'Payments',
    storeDelivery: 'Delivery',
    storeDomain: 'Domain',
    storeIntegrations: 'Integrations',
  },
  creatorDashboard: {
    title: 'Dashboard',
    subtitle: 'Your stats and earnings',
    clicks: 'Clicks',
    conversions: 'Conversions',
    earnings: 'Earnings',
    topMerchants: 'Top merchants',
    noMerchants: 'No active merchants yet',
    noMerchantsHint: 'Go to My Links to get tracking links',
    statsError: 'Failed to load stats.',
    tableNum: '#',
    tableMerchant: 'Merchant',
    tableClicks: 'Clicks',
    tableConversions: 'Conversions',
    tableCommission: 'Commission',
    days7: '7 days',
    days30: '30 days',
    days90: '90 days',
  },
  merchantDashboard: {
    title: 'Dashboard',
    subtitle: 'Your stats and balance',
    clicks: 'Clicks',
    conversions: 'Conversions',
    commissionPaid: 'Commission paid',
    balance: 'Current balance',
    topCreators: 'Top creators',
    noCreators: 'No active creators yet',
    noCreatorsHint: 'Creators can find your self-link',
    statsError: 'Failed to load stats.',
    tableNum: '#',
    tableCreator: 'Creator',
    tableClicks: 'Clicks',
    tableConversions: 'Conversions',
    tableCommission: 'Commission',
    days7: '7 days',
    days30: '30 days',
    days90: '90 days',
  },
  myLinks: {
    title: 'My Links',
    subtitle: 'Merchant → button → link. Share it.',
    featuredBrands: '✦ Featured brands',
    allBrands: 'All brands',
    getLink: 'Get link',
    commission: '% commission',
    loadError: 'Failed to load merchants.',
    noMerchants: 'No merchants found',
    trackingLinkLabel: 'Your tracking link',
    modalHint: 'Share this link with your followers. Every sale made through this link counts as your commission.',
  },
  earnings: {
    title: 'Earnings',
    subtitle: 'Your commission history',
    history: 'Earnings history',
    noEarnings: 'No commissions yet',
    noEarningsHint: 'Share your links and sales will appear here',
    loadError: 'Failed to load data.',
    colDate: 'Date',
    colMerchant: 'Merchant',
    colOrder: 'Order',
    colCommission: 'Your Earnings',
    colSource: 'Source',
    colStatus: 'Status',
    allTime: 'All time',
    monthlySales: 'sales',
    monthlyEarned: 'earned',
    monthlyBreakdown: 'Monthly breakdown',
  },
  conversionsPage: {
    title: 'Conversions',
    subtitle: 'All conversions from creators',
    history: 'Conversion history',
    noConversions: 'No conversions yet',
    noConversionsHint: 'Creators will share links and sales will appear',
    loadError: 'Failed to load data.',
    colDate: 'Date',
    colCreator: 'Creator',
    colOrder: 'Order',
    colCommission: 'You Pay',
    colSource: 'Source',
    colStatus: 'Status',
    allTime: 'All time',
    monthlySales: 'sales',
    monthlyOwed: 'total owed',
    monthlyBreakdown: 'Monthly breakdown',
  },
  status: {
    Pending: 'Pending',
    Confirmed: 'Confirmed',
    Rejected: 'Rejected',
    Paid: 'Paid',
  },
  source: {
    ManualReport: 'Manual',
    JsSnippet: 'JS',
    WooCommercePlugin: 'WooC.',
    Api: 'API',
  },
  merchantsPage: {
    badge: '⬡ Brands',
    title: 'Partner shops',
    subtitle: 'Pick a brand, get your link and code, share it — earn commission.',
    featuredBrands: '✦ Featured brands',
    allShops: 'All shops',
    noShops: 'No shops yet.',
    websiteLink: 'Website ↗',
    getLink: 'Get link →',
    getLinkBtn: 'Get link',
    forBrand: 'Your link for this brand',
    trackingLinkLabel: 'Your tracking link',
    modalHint: 'Share this link with your followers. Every sale through this link counts as your commission.',
    viewProfile: 'Profile',
    commissionRate: 'Commission rate',
    partnerSince: 'Partner since',
    noDescription: 'No description',
  },
  reportSale: {
    title: 'Report Sale',
    subtitle: 'Manually add a conversion',
    creatorLabel: 'Creator (slug or name)',
    creatorPlaceholder: 'e.g. giorgi123',
    amountLabel: 'Order amount',
    amountPlaceholder: 'e.g. 49.99',
    currencyLabel: 'Currency',
    orderIdLabel: 'Order ID (optional)',
    orderIdPlaceholder: 'e.g. ORD-1234',
    submit: 'Add conversion',
    submitting: 'Adding…',
    success: 'Conversion added successfully!',
    error: 'Failed to add conversion.',
  },
  onboarding: {
    title: 'Welcome to NipNip!',
    subtitle: 'Complete your profile to get started.',
    nameLabel: 'Name / brand name',
    namePlaceholder: 'e.g. Giorgi Lomidze',
    slugLabel: 'Slug (your unique URL)',
    slugPlaceholder: 'e.g. giorgi',
    slugHint: 'Used in your tracking links',
    instagramLabel: 'Instagram handle',
    instagramPlaceholder: '@giorgi',
    tiktokLabel: 'TikTok handle',
    tiktokPlaceholder: '@giorgi',
    submit: 'Save profile',
    submitting: 'Saving…',
    error: 'Failed to save profile.',
  },
  settings: {
    title: 'Settings',
    profileSection: 'Profile',
    socialSection: 'Social accounts',
    notificationsSection: 'Notifications',
    nameLabel: 'Name',
    slugLabel: 'Slug',
    instagramLabel: 'Instagram',
    tiktokLabel: 'TikTok',
    youtubeLabel: 'YouTube',
    facebookLabel: 'Facebook',
    xLabel: 'X (Twitter)',
    linkedinLabel: 'LinkedIn',
    followersLabel: 'Followers',
    websiteLabel: 'Website',
    descriptionLabel: 'Description',
    logoLabel: 'Logo URL',
    commissionLabel: 'Commission %',
    notificationEmailLabel: 'Notification email',
    notificationEmailHint: 'You will receive an email at this address for every new sale',
    saveSuccess: 'Changes saved!',
    saveError: 'Failed to save.',
    avatarSection: 'Profile photo',
    uploadPhoto: 'Upload photo',
    uploadHint: 'JPG, PNG, WEBP · max 5 MB',
    uploading: 'Uploading…',
    uploadError: 'Upload failed.',
    optional: '(optional)',
    followersPlaceholder: 'Followers',
    clickToSelect: 'PNG, JPG, WEBP · click to select',
    readOnly: '(cannot be changed)',
    profileSubtitle: 'Edit your profile',
  },
  creatorsPage: {
    badge: '◉ Creators',
    title: 'Our Creators',
    subtitle: 'Talented people who sell brands through NipNip and earn commissions.',
    featuredCreators: '✦ Featured Creators',
    allCreators: 'All creators',
    noCreators: 'No creators yet.',
    viewProfile: 'Profile',
    noSocials: 'No socials linked',
    memberSince: 'Member since',
    socials: 'Social accounts',
  },
  carousel: {
    trackingLinkLabel: 'Your tracking link',
    forBrand: 'Your link for this brand',
    modalHint: 'Share this link with your followers. Every sale through this link counts as your commission.',
    getLink: 'Get link →',
  },
  signInRequired: {
    title: 'Sign in required',
    body: 'You need to sign in before you can get your tracking link.',
    cta: 'Sign in',
  },
  detail: {
    title: 'Conversion details',
    notFound: 'Conversion not found.',
    statusLabel: 'Status',
    yourCommission: 'Your Earnings',
    commission: 'You Pay',
    saleAmount: 'Sale amount',
    merchant: 'Merchant',
    creator: 'Creator',
    orderId: 'Order ID',
    sourceLabel: 'Source',
    backEarnings: 'Earnings',
    backConversions: 'Conversions',
  },
  sourceFull: {
    ManualReport: 'Manual entry',
    JsSnippet: 'JS Snippet',
    WooCommercePlugin: 'WooCommerce',
    Api: 'API',
  },
  integration: {
    title: 'Website Integration',
    subtitle: 'Get NipNip tracking running on your website.',
    platformSelector: 'Choose your platform',
    platformWoo: 'WooCommerce',
    platformCustom: 'Custom Website',
    wooApiKeyTitle: 'API Key',
    wooApiKeyDesc: 'Enter this key in the plugin settings.',
    wooDownloadBtn: 'Download Plugin',
    wooComingSoon: 'Coming soon.',
    wooStep1: '1. Download the plugin',
    wooStep1Desc: 'Download the NipNip WooCommerce plugin using the button below.',
    wooStep2: '2. Install in WordPress',
    wooStep2Desc: 'WordPress Admin → Plugins → Add New → Upload Plugin → upload the .zip → Install Now → Activate.',
    wooStep3: '3. Enter your API key',
    wooStep3Desc: 'In the plugin settings (WooCommerce → NipNip Settings) paste the API key shown above.',
    wooDone: '4. Done!',
    wooDoneDesc: 'Tracking is fully automatic — NipNip records every order automatically.',
    snippet1Label: 'Snippet 1 — Global layout',
    snippet1Desc: 'Paste once in your shared site footer or HTML template. Stores the NipNip ref in a cookie in the visitor browser.',
    snippet2Label: 'Snippet 2 — Order confirmation page',
    snippet2Desc: 'Paste only on your order confirmation / thank-you page.',
    cookieNote: 'The _nn_ref cookie remembers which creator referred this visitor — the snippet reads it automatically.',
    examplesTitle: 'Injecting ORDER_ID and AMOUNT',
    examplesDesc: 'Replace ORDER_ID and AMOUNT with real values from your backend.',
    phpTab: 'PHP',
    jsTab: 'JavaScript',
    copySnippet: 'Copy',
    copied: 'Copied!',
    testBtn: 'Test Connection',
    testing: 'Testing…',
    connectedBadge: 'Connected',
    notConnectedBadge: 'Not Connected',
    testHint: 'Verify that your API key is valid and the backend is reachable.',
    connectedHint: 'API key is valid. Connection successful.',
    notConnectedHint: 'Connection failed. Check your API key.',
    loadError: 'Failed to load snippets.',
    noWebsiteNote: 'No website? You can report sales manually from the Dashboard',
    noWebsiteLink: 'Report sale manually →',
    platformShopify: 'Shopify',
    shopifyStep1Label: 'Step 1 — theme.liquid (before </head>)',
    shopifyStep1Desc: 'Online Store (left sidebar) → 3 dots on your active theme → Edit code → Layout folder → theme.liquid → paste before </head>.',
    shopifyStep2Label: 'Step 2 — Custom Pixel (Customer Events)',
    shopifyStep2Desc: 'Settings → Customer events → Custom pixels → Add custom pixel → name it Nipnip Webhook → paste the code → Add pixel.',
    shopifyLiquidNote: 'checkout.order.id, checkout.totalPrice.amount and checkout.totalPrice.currencyCode are Shopify Customer Events API fields — they are filled automatically with real order data.',
    platformStore: 'NipNip Store',
    storeTabTitle: 'Your NipNip Store',
    storeTabDesc: 'No code to install — since NipNip already runs your storefront, tracking is built in. Just flip the switch.',
    storeToggleLabel: 'Affiliate tracking',
    storeToggleOnDesc: 'On — creator links redirect straight to your store, and every completed order is tracked and attributed automatically.',
    storeToggleOffDesc: 'Off — creator links will not track sales made on your NipNip store.',
    storeNoStoreNote: "You haven't created a NipNip store yet.",
    storeNoStoreLink: 'Set up your store →',
  },
}
