export const ka = {
  nav: {
    brands: 'ბრენდები',
    creators: 'კრეატორები',
    howItWorks: 'როგორ მუშაობს',
    faq: 'FAQ',
    signIn: 'შესვლა',
    signUp: 'რეგისტრაცია',
    dashboard: 'Dashboard',
    admin: 'Admin',
  },
  footer: {
    tagline: 'ქართული ეფილიატ პლატფორმა კრეატორებისა და მერჩანტებისთვის.',
    platform: 'პლატფორმა',
    forCreators: 'კრეატორებს',
    forMerchants: 'მერჩანტებს',
    copyright: 'შექმნილია კრეატორებისთვის',
    about: 'შესახებ',
    howItWorks: 'როგორ მუშაობს',
    faq: 'FAQ',
    contact: 'კონტაქტი',
    signUp: 'რეგისტრაცია',
    merchants: 'მერჩანტები',
    creatorDashboard: 'კრეატორის პანელი',
    joinAsMerchant: 'ჩართვა',
    merchantDashboard: 'მერჩანტის პანელი',
    poweredBy: 'powered by',
  },
  landing: {
    badge: 'ონლაინ მაღაზია + აფილიატ მარკეტინგი, ერთად',
    headline1: 'გაყიდე მეტი.',
    headline2: 'იმუშავე ნაკლები.',
    tagline: 'შენი მაღაზია, მარაგის მართვა, AI ჩატ-აგენტი და კრეატორების ქსელი — ყველაფერი ერთ პლატფორმაზე.',
    ctaSignUp: 'დაიწყე უფასოდ',
    ctaHowItWorks: 'როგორ მუშაობს',
    heroChatQuestion: '42-ე ზომაშია?',
    heroChatAnswer: 'დიახ, მარაგშია ✅',
    heroCreatorsSelling: '3 კრეატორი ყიდის',
    heroCommissionLabel: 'კომისია',
    heroAddToCart: '+ კალათა',
    featuredBrandsLabel: '✦ გამორჩეული ბრენდები',
    partnerShops: 'პარტნიორი მაღაზიები',
    viewAll: 'ყველა ნახვა',
    merchantsBadge: 'მერჩანტებისთვის',
    merchantsTitle: 'ყველაფერი, რაც მაღაზიას სჭირდება',
    merchantsAccent: 'ერთ პლატფორმაზე.',
    merchantFeature1Title: 'ონლაინ მაღაზია',
    merchantFeature1Body: 'გახსენი ბრენდირებული მაღაზია რამდენიმე წუთში — დიზაინი, კატეგორიები, გვერდები, ყველაფერი შენს კონტროლში.',
    merchantFeature2Title: 'მარაგის მართვა',
    merchantFeature2Body: 'აკონტროლე მარაგი ვარიანტების მიხედვით — ზომა, ფერი, რაც არ უნდა გყიდდეს. აღარასდროს გაყიდო ის, რაც აღარ გაქვს.',
    merchantFeature3Title: 'Facebook და Instagram',
    merchantFeature3Body: 'შემოიტანე პროდუქტები პირდაპირ პოსტებიდან, ან გამოაქვეყნე ორივე პლატფორმაზე ერთი კლიკით.',
    merchantFeature4Title: 'AI შეტყობინებების აგენტი',
    merchantFeature4Body: 'AI აგენტი ავტომატურად პასუხობს მომხმარებლებს Messenger-ში — ამოწმებს მარაგს, პასუხობს კითხვებს და ქმნის შეკვეთებს დასადასტურებლად.',
    merchantFeature5Title: 'აფილიატ მარკეტინგი',
    merchantFeature5Body: 'მიეცი კრეატორებს საშუალება გაყიდონ შენი პროდუქტები საკუთარი აუდიტორიისთვის — გადაუხადე მხოლოდ შედეგზე.',
    howItWorksBadge: 'კრეატორებისთვის',
    howItWorksTitle: 'სამი ნაბიჯი',
    howItWorksAccent: 'პირველ კომისიამდე.',
    step1Title: 'დარეგისტრირდი',
    step1Body: 'გახსენი უფასო ანგარიში რამდენიმე წამში. ბარათი არ გჭირდება.',
    step2Title: 'აიღე ლინკი',
    step2Body: 'მიიღე უნიკალური პრომო კოდი ან სათვალთვალო ლინკი ნებისმიერი პარტნიორი მერჩანტისთვის.',
    step3Title: 'გამოიმუშავე',
    step3Body: 'ყოველი გაყიდვა — კომისია. შემოსავალი ჩანს ანგარიშზე რეალურ დროში.',
    ctaTitle: 'მზად ხარ\nდასაწყებად?',
    ctaBody: 'მაღაზიის აშენება გინდა თუ კრეატორად შემოსავლის მიღება — შემოუერთდი NipNip-ს დღესვე.',
    ctaFree: 'უფასოდ დარეგისტრირდი',
  },
  common: {
    save: 'შენახვა',
    cancel: 'გაუქმება',
    close: 'დახურვა',
    loading: 'იტვირთება…',
    submitting: 'იგზავნება…',
    error: 'დაფიქსირდა შეცდომა. სცადეთ თავიდან.',
    clear: 'გასუფთავება',
    copy: 'კოპირება',
    copied: 'კოპირდა!',
    prev: 'წინა',
    next: 'შემდეგი',
    records: 'ჩანაწერი',
    total: 'სულ',
  },
  sidebar: {
    creatorBadge: 'კრეატორი',
    merchantBadge: 'მერჩანტი',
    dashboard: 'მთავარი',
    myLinks: 'ჩემი ლინკები',
    earnings: 'შემოსავლები',
    payouts: 'გადახდები',
    conversions: 'კონვერსიები',
    reportSale: 'გაყიდვის დამატება',
    store: 'მაღაზია',
    settings: 'პარამეტრები',
    browseMarketplace: 'მერჩანტები',
    marketplace: 'მარკეტფლეისი',
    integration: 'ინტეგრაცია',
    affiliateGroup: 'აფილიატ მარკეტინგი',
    onlineStoreGroup: 'ონლაინ მაღაზია',
    aiAgentsGroup: 'AI აგენტები',
    messagingAgent: 'შეტყობინებების აგენტი',
    storeOverview: 'დეტალები',
    storeOrders: 'შეკვეთები',
    storeCategories: 'კატეგორიები',
    storePages: 'გვერდები',
    storeDesign: 'დიზაინი',
    storeProducts: 'პროდუქტები',
    storeMessages: 'შეტყობინებები',
    storeContact: 'კონტაქტი და სოციალები',
    storePayments: 'გადახდები',
    storeDelivery: 'მიწოდება',
    storeDomain: 'დომენი',
    storeIntegrations: 'ინტეგრაციები',
  },
  admin: {
    badge: 'Admin',
    overview: 'მიმოხილვა',
    merchants: 'მერჩანტები',
    creators: 'კრეატორები',
    conversions: 'კონვერსიები',
    payouts: 'გადახდები',
    demoLogin: 'დემო შესვლა',
    notAuthorized: 'თქვენ არ გაქვთ ამ გვერდზე წვდომა.',
    goHome: 'მთავარ გვერდზე დაბრუნება',
  },
  creatorDashboard: {
    title: 'Dashboard',
    subtitle: 'შენი სტატისტიკა და შემოსავლები',
    clicks: 'კლიკები',
    conversions: 'კონვერსიები',
    earnings: 'შემოსავალი',
    topMerchants: 'ტოპ მერჩანტები',
    noMerchants: 'ჯერ არ გაქვს აქტიური მერჩანტები',
    noMerchantsHint: 'My Links-ზე გადადი, რომ ლინკები მიიღო',
    statsError: 'სტატისტიკის ჩატვირთვა ვერ მოხერხდა.',
    tableNum: '#',
    tableMerchant: 'მერჩანტი',
    tableClicks: 'კლიკები',
    tableConversions: 'კონვერსიები',
    tableCommission: 'კომისია',
    days7: '7 დღე',
    days30: '30 დღე',
    days90: '90 დღე',
  },
  merchantDashboard: {
    title: 'Dashboard',
    subtitle: 'შენი სტატისტიკა და ბალანსი',
    clicks: 'კლიკები',
    conversions: 'კონვერსიები',
    commissionPaid: 'გადახდილი კომისია',
    balance: 'მიმდინარე ბალანსი',
    topCreators: 'ტოპ კრეატორები',
    noCreators: 'ჯერ არ გაქვს აქტიური კრეატორები',
    noCreatorsHint: 'კრეატორები შეიძლება ნახონ შენი სელფ-ლინკი',
    statsError: 'სტატისტიკის ჩატვირთვა ვერ მოხერხდა.',
    tableNum: '#',
    tableCreator: 'კრეატორი',
    tableClicks: 'კლიკები',
    tableConversions: 'კონვერსიები',
    tableCommission: 'კომისია',
    days7: '7 დღე',
    days30: '30 დღე',
    days90: '90 დღე',
  },
  myLinks: {
    title: 'My Links',
    subtitle: 'მერჩანტი → ღილაკი → ლინკი. გაუზიარე სხვებს.',
    featuredBrands: '✦ გამორჩეული ბრენდები',
    allBrands: 'ყველა ბრენდი',
    getLink: 'ლინკის მიღება',
    commission: '% კომისია',
    loadError: 'მერჩანტების ჩატვირთვა ვერ მოხერხდა.',
    noMerchants: 'მერჩანტები არ მოიძებნა',
    trackingLinkLabel: 'შენი ტრეკინგ ლინკი',
    modalHint: 'გაუზიარე ეს ლინკი შენს მიმდევრებს. ყოველი გაყიდვა, რომელიც ამ ლინკის გავლით მოხდება, ჩაითვლება შენს კომისიად.',
  },
  earnings: {
    title: 'Earnings',
    subtitle: 'შენი კომისიების ისტორია',
    history: 'შემოსავლების ისტორია',
    noEarnings: 'კომისიები ჯერ არ გაქვს',
    noEarningsHint: 'ლინკები გაავრცელე და გაყიდვები გამოჩნდება',
    loadError: 'მონაცემების ჩატვირთვა ვერ მოხერხდა.',
    colDate: 'თარიღი',
    colMerchant: 'მერჩანტი',
    colOrder: 'შეკვეთა',
    colCommission: 'შენი შემოსავალი',
    colSource: 'წყარო',
    colStatus: 'სტატუსი',
    allTime: 'ყველა დრო',
    monthlySales: 'გაყიდვა',
    monthlyEarned: 'შემოსავალი',
    monthlyBreakdown: 'თვიური სტატისტიკა',
  },
  conversionsPage: {
    title: 'Conversions',
    subtitle: 'კრეატორებისგან შემოსული ყველა კონვერსია',
    history: 'კონვერსიების ისტორია',
    noConversions: 'კონვერსიები ჯერ არ გაქვს',
    noConversionsHint: 'კრეატორები ლინკებს გაავრცელებენ და გაყიდვები გამოჩნდება',
    loadError: 'მონაცემების ჩატვირთვა ვერ მოხერხდა.',
    colDate: 'თარიღი',
    colCreator: 'კრეატორი',
    colOrder: 'შეკვეთა',
    colCommission: 'გადასახდელი',
    colSource: 'წყარო',
    colStatus: 'სტატუსი',
    allTime: 'ყველა დრო',
    monthlySales: 'გაყიდვა',
    monthlyOwed: 'სულ გადასახდელი',
    monthlyBreakdown: 'თვიური სტატისტიკა',
  },
  status: {
    Pending: 'მოლოდინში',
    Confirmed: 'დადასტურებული',
    Rejected: 'უარყოფილი',
    Paid: 'გადახდილი',
  },
  source: {
    ManualReport: 'ხელით',
    JsSnippet: 'JS',
    WooCommercePlugin: 'WooC.',
    Api: 'API',
  },
  merchantsPage: {
    badge: '⬡ ბრენდები',
    title: 'პარტნიორი მაღაზიები',
    subtitle: 'აირჩიე ბრენდი, მიიღე შენი ლინკი და კოდი, გაუზიარე — შოვე კომისია.',
    featuredBrands: '✦ გამორჩეული ბრენდები',
    allShops: 'ყველა მაღაზია',
    noShops: 'მაღაზიები ჯერ არ არის.',
    websiteLink: 'ვებ-გვერდი ↗',
    getLink: 'ლინკის მიღება →',
    getLinkBtn: 'ლინკის მიღება',
    forBrand: 'შენი ლინკი ამ ბრენდისთვის',
    trackingLinkLabel: 'შენი ტრეკინგ ლინკი',
    modalHint: 'გაუზიარე ეს ლინკი შენს მიმდევრებს. ყოველი გაყიდვა ამ ლინკის გავლით ჩაითვლება შენს კომისიად.',
    viewProfile: 'პროფილი',
    commissionRate: 'კომისიის განაკვეთი',
    partnerSince: 'პარტნიორია',
    noDescription: 'აღწერა არ არის',
  },
  reportSale: {
    title: 'Report Sale',
    subtitle: 'ხელით კონვერსიის დამატება',
    creatorLabel: 'კრეატორი (slug ან სახელი)',
    creatorPlaceholder: 'მაგ. giorgi123',
    amountLabel: 'შეკვეთის თანხა',
    amountPlaceholder: 'მაგ. 49.99',
    currencyLabel: 'ვალუტა',
    orderIdLabel: 'შეკვეთის ID (არასავალდებულო)',
    orderIdPlaceholder: 'მაგ. ORD-1234',
    submit: 'კონვერსიის დამატება',
    submitting: 'ემატება…',
    success: 'კონვერსია წარმატებით დაემატა!',
    error: 'კონვერსიის დამატება ვერ მოხერხდა.',
  },
  onboarding: {
    title: 'მოგესალმება NipNip-ზე!',
    subtitle: 'შეავსე შენი პროფილი, რომ დაიწყო.',
    nameLabel: 'სახელი / ბრენდის სახელი',
    namePlaceholder: 'მაგ. გიორგი ლომიძე',
    slugLabel: 'Slug (შენი უნიკალური URL)',
    slugPlaceholder: 'მაგ. giorgi',
    slugHint: 'გამოიყენება შენს ტრეკინგ ლინკებში',
    instagramLabel: 'Instagram handle',
    instagramPlaceholder: '@giorgi',
    tiktokLabel: 'TikTok handle',
    tiktokPlaceholder: '@giorgi',
    submit: 'პროფილის შენახვა',
    submitting: 'ინახება…',
    error: 'პროფილის შენახვა ვერ მოხერხდა.',
  },
  settings: {
    title: 'Settings',
    profileSection: 'პროფილი',
    socialSection: 'სოციალური ქსელები',
    notificationsSection: 'შეტყობინებები',
    nameLabel: 'სახელი',
    slugLabel: 'Slug',
    instagramLabel: 'Instagram',
    tiktokLabel: 'TikTok',
    youtubeLabel: 'YouTube',
    facebookLabel: 'Facebook',
    xLabel: 'X (Twitter)',
    linkedinLabel: 'LinkedIn',
    followersLabel: 'მიმდევრების რაოდენობა',
    websiteLabel: 'ვებ-საიტი',
    descriptionLabel: 'აღწერა',
    logoLabel: 'ლოგოს URL',
    commissionLabel: 'კომისიის %',
    notificationEmailLabel: 'შეტყობინების ელფოსტა',
    notificationEmailHint: 'ამ მისამართზე მივა ელფოსტა ყოველი ახალი გაყიდვის შესახებ',
    saveSuccess: 'ცვლილებები შენახულია!',
    saveError: 'შენახვა ვერ მოხერხდა.',
    avatarSection: 'პროფილის ფოტო',
    uploadPhoto: 'ფოტოს ატვირთვა',
    uploadHint: 'JPG, PNG, WEBP · მაქს. 5 MB',
    uploading: 'იტვირთება…',
    uploadError: 'ატვირთვა ვერ მოხერხდა.',
    optional: '(სურვილისამებრ)',
    followersPlaceholder: 'მიმდევრები',
    clickToSelect: 'PNG, JPG, WEBP · კლიკი ასარჩევად',
    readOnly: '(შეცვლა შეუძლებელია)',
    profileSubtitle: 'შენი პროფილის რედაქტირება',
  },
  creatorsPage: {
    badge: '◉ კრეატორები',
    title: 'ჩვენი კრეატორები',
    subtitle: 'ნიჭიერი ადამიანები, ვინც NipNip-ის გზით ყიდის ბრენდებს და გამოიმუშავებს კომისიებს.',
    featuredCreators: '✦ გამორჩეული კრეატორები',
    allCreators: 'ყველა კრეატორი',
    noCreators: 'კრეატორები ჯერ არ არის.',
    viewProfile: 'პროფილი',
    noSocials: 'სოციალური ქსელი არ არის',
    memberSince: 'წევრია',
    socials: 'სოციალური ქსელები',
  },
  carousel: {
    trackingLinkLabel: 'შენი ტრეკინგ ლინკი',
    forBrand: 'შენი ლინკი ამ ბრენდისთვის',
    modalHint: 'გაუზიარე ეს ლინკი შენს მიმდევრებს. ყოველი გაყიდვა ამ ლინკის გავლით ჩაითვლება შენს კომისიად.',
    getLink: 'ლინკის მიღება →',
  },
  signInRequired: {
    title: 'შესვლა საჭიროა',
    body: 'ლინკის მისაღებად ჯერ შეხვიდეთ ანგარიშში.',
    cta: 'შესვლა',
  },
  detail: {
    title: 'კონვერსიის დეტალები',
    notFound: 'კონვერსია ვერ მოიძებნა.',
    statusLabel: 'სტატუსი',
    yourCommission: 'შენი შემოსავალი',
    commission: 'გადასახდელი',
    saleAmount: 'გაყიდვის თანხა',
    merchant: 'მერჩანტი',
    creator: 'კრეატორი',
    orderId: 'შეკვეთის ID',
    sourceLabel: 'წყარო',
    backEarnings: 'Earnings',
    backConversions: 'Conversions',
  },
  sourceFull: {
    ManualReport: 'ხელით შეყვანილი',
    JsSnippet: 'JS Snippet',
    WooCommercePlugin: 'WooCommerce',
    Api: 'API',
  },
  integration: {
    title: 'ვებ-საიტის ინტეგრაცია',
    subtitle: 'NipNip ტრეკინგის გაშვება შენს საიტზე.',
    platformSelector: 'აირჩიე პლატფორმა',
    platformWoo: 'WooCommerce',
    platformCustom: 'Custom Website',
    wooApiKeyTitle: 'API კლავიში',
    wooApiKeyDesc: 'Plugin-ის პარამეტრებში ჩასვი ეს კლავიში.',
    wooDownloadBtn: 'Plugin-ის ჩამოტვირთვა',
    wooComingSoon: 'მალე ხელმისაწვდომი იქნება.',
    wooStep1: '1. Plugin-ის ჩამოტვირთვა',
    wooStep1Desc: 'ჩამოტვირთე NipNip WooCommerce Plugin ქვემოთ მოცემული ღილაკით.',
    wooStep2: '2. WordPress-ში ინსტალაცია',
    wooStep2Desc: 'WordPress Admin → Plugins → Add New → Upload Plugin → ატვირთე .zip ფაილი → Install Now → Activate.',
    wooStep3: '3. API კლავიშის შეყვანა',
    wooStep3Desc: 'Plugin-ის პარამეტრებში (WooCommerce → NipNip Settings) ჩასვი ზემოთ მოცემული API კლავიში.',
    wooDone: '4. მზადაა!',
    wooDoneDesc: 'ტრეკინგი სრულად ავტომატურია — NipNip-ი ყოველ შეკვეთას ავტომატურად ჩაწერს.',
    snippet1Label: 'სნიპეტი 1 — გლობალური ლეიაუტი',
    snippet1Desc: 'ჩასვი ერთხელ — საიტის საერთო footer-ში ან HTML შაბლონში. ინახავს NipNip ref-ს ვიზიტორის ბრაუზერის cookie-ში.',
    snippet2Label: 'სნიპეტი 2 — შეკვეთის გვერდი',
    snippet2Desc: 'ჩასვი მხოლოდ შეკვეთის დადასტურების (thank you) გვერდზე.',
    cookieNote: '_nn_ref cookie-ი ახსოვს, რომელმა კრეატორმა მოიყვანა ეს მომხმარებელი — სნიპეტი ავტომატურად კითხულობს მას.',
    examplesTitle: 'ORDER_ID და AMOUNT-ის ჩასმა',
    examplesDesc: 'შეცვალე ORDER_ID და AMOUNT შენი back-end-ის ცვლადებით.',
    phpTab: 'PHP',
    jsTab: 'JavaScript',
    copySnippet: 'კოპირება',
    copied: 'კოპირდა!',
    testBtn: 'კავშირის შემოწმება',
    testing: 'შემოწმება...',
    connectedBadge: 'დაკავშირებულია',
    notConnectedBadge: 'კავშირი არ არის',
    testHint: 'გადაამოწმე API კლავიში და სერვერთან კავშირი.',
    connectedHint: 'API კლავიში ვალიდურია. კავშირი წარმატებულია.',
    notConnectedHint: 'კავშირი ვერ დამყარდა. გადაამოწმე API კლავიში.',
    loadError: 'სნიპეტები ვერ ჩაიტვირთა.',
    noWebsiteNote: 'თუ არ გაქვს ვებ-საიტი, შეგიძლია გაყიდვები ხელით შეიტანო Dashboard-დან',
    noWebsiteLink: 'გაყიდვის ხელით შეტანა →',
    platformShopify: 'Shopify',
    shopifyStep1Label: 'ნაბიჯი 1 — theme.liquid (</head> ტეგის წინ)',
    shopifyStep1Desc: 'Online Store (მარცხენა პანელი) → 3 წერტილი აქტიურ თემაზე → Edit code → Layout → theme.liquid → ჩასვი </head> ტეგის წინ.',
    shopifyStep2Label: 'ნაბიჯი 2 — Custom Pixel (Customer Events)',
    shopifyStep2Desc: 'Settings → Customer events → Custom pixels → Add custom pixel → სახელი: Nipnip Webhook → ჩასვი კოდი → Add pixel.',
    shopifyLiquidNote: 'checkout.order.id, checkout.totalPrice.amount და checkout.totalPrice.currencyCode Shopify Customer Events API-ს ველებია — ისინი ავტომატურად ივსება შეკვეთის რეალური მონაცემებით.',
    platformStore: 'NipNip მაღაზია',
    storeTabTitle: 'შენი NipNip მაღაზია',
    storeTabDesc: 'კოდის ჩასმა არ არის საჭირო — რადგან შენი მაღაზია უკვე NipNip-ზეა, ტრეკინგი ჩაშენებულია. უბრალოდ ჩართე.',
    storeToggleLabel: 'აფილიატ ტრეკინგი',
    storeToggleOnDesc: 'ჩართულია — კრეატორის ლინკები პირდაპირ შენს მაღაზიაზე გადამისამართებს და ყოველი დასრულებული შეკვეთა ავტომატურად ტრექდება.',
    storeToggleOffDesc: 'გამორთულია — კრეატორის ლინკები არ ჩაწერენ გაყიდვებს შენს NipNip მაღაზიაზე.',
    storeNoStoreNote: 'შენ ჯერ არ გაქვს შექმნილი NipNip მაღაზია.',
    storeNoStoreLink: 'მაღაზიის შექმნა →',
  },
} as const

type DeepStringify<T> = { [K in keyof T]: T[K] extends object ? DeepStringify<T[K]> : string }

export type Strings = DeepStringify<typeof ka>
