import type { Strings } from './ka'

export const ru: Strings = {
  nav: {
    brands: 'Бренды',
    creators: 'Авторы',
    howItWorks: 'Как это работает',
    faq: 'FAQ',
    signIn: 'Войти',
    signUp: 'Регистрация',
    dashboard: 'Панель',
    admin: 'Admin',
  },
  footer: {
    tagline: 'Грузинская affiliate-платформа для авторов и магазинов.',
    platform: 'Платформа',
    forCreators: 'Авторам',
    forMerchants: 'Магазинам',
    copyright: 'Создано для авторов',
    about: 'О нас',
    howItWorks: 'Как это работает',
    faq: 'FAQ',
    contact: 'Контакт',
    signUp: 'Регистрация',
    merchants: 'Магазины',
    creators: 'Авторы',
    creatorDashboard: 'Панель автора',
    joinAsMerchant: 'Присоединиться',
    merchantDashboard: 'Панель магазина',
    poweredBy: 'powered by',
    privacy: 'Политика конфиденциальности',
    terms: 'Условия использования',
    dataDeletion: 'Удаление данных',
  },
  websiteInquiry: {
    heading: 'Свяжитесь с нами',
    subheading: 'Хотите свой собственный сайт? Напишите нам, и мы поможем вам его создать.',
    namePlaceholder: 'Имя',
    emailPlaceholder: 'Эл. почта',
    phonePlaceholder: 'Номер телефона',
    messagePlaceholder: 'Сообщение',
    contactHint: 'Укажите эл. почту или номер телефона',
    submit: 'Отправить',
    submitting: 'Отправка...',
    success: 'Спасибо! Мы скоро свяжемся с вами.',
    sendAnother: 'Отправить ещё одно сообщение',
    errorName: 'Имя обязательно.',
    errorMessage: 'Сообщение обязательно.',
    errorContact: 'Укажите эл. почту или номер телефона.',
    errorEmail: 'Неверный формат эл. почты.',
    errorGeneric: 'Произошла ошибка. Попробуйте снова.',
  },
  landing: {
    badge: 'Онлайн-магазин + affiliate-маркетинг, вместе',
    headline1: 'Продавай больше.',
    headline2: 'Работай меньше.',
    tagline: 'Магазин, учёт остатков, AI-агент для чатов и сеть авторов — всё на одной платформе.',
    ctaSignUp: 'Начать бесплатно',
    ctaHowItWorks: 'Как это работает',
    heroChatQuestion: 'Есть 42 размер?',
    heroChatAnswer: 'Да, есть в наличии ✅',
    heroCreatorsSelling: '3 автора продают',
    heroCommissionLabel: 'комиссия',
    heroAddToCart: '+ Корзина',
    featuredBrandsLabel: '✦ Избранные бренды',
    partnerShops: 'Магазины-партнёры',
    viewAll: 'Смотреть все',
    merchantsBadge: 'Для продавцов',
    merchantsTitle: 'Всё, что нужно магазину',
    merchantsAccent: 'в одной платформе.',
    merchantFeature1Title: 'Онлайн-магазин',
    merchantFeature1Body: 'Запусти брендированный магазин за пару минут — дизайн, категории, страницы — всё под твоим контролем.',
    merchantFeature2Title: 'Учёт остатков',
    merchantFeature2Body: 'Отслеживай остатки по вариантам — размер, цвет, что угодно. Больше никогда не продашь то, чего нет в наличии.',
    merchantFeature3Title: 'Facebook и Instagram',
    merchantFeature3Body: 'Импортируй товары прямо из постов или публикуй на обеих платформах в один клик.',
    merchantFeature4Title: 'AI-агент для сообщений',
    merchantFeature4Body: 'AI-агент сам отвечает клиентам в Messenger — проверяет остатки, отвечает на вопросы и создаёт заказы на твоё подтверждение.',
    merchantFeature5Title: 'Affiliate-маркетинг',
    merchantFeature5Body: 'Позволь авторам продавать твои товары своей аудитории — платишь только за результат.',
    howItWorksBadge: 'Для авторов',
    howItWorksTitle: 'Три шага',
    howItWorksAccent: 'до первой комиссии.',
    step1Title: 'Зарегистрируйся',
    step1Body: 'Открой бесплатный аккаунт за несколько секунд. Карта не нужна.',
    step2Title: 'Получи ссылку',
    step2Body: 'Получи уникальный промокод или реферальную ссылку для любого магазина-партнёра.',
    step3Title: 'Зарабатывай',
    step3Body: 'Каждая продажа — это комиссия. Доход виден в аккаунте в реальном времени.',
    pricingBadge: 'Цены',
    pricingTitle: 'Простые цены',
    pricingAccent: 'для всех.',
    pricingPerMonth: 'месяц',
    pricingTrial: 'Первые 3 месяца',
    pricingThen: 'затем',
    pricingPopular: 'Популярный',
    pricingAffiliateTitle: 'Affiliate-маркетинг',
    pricingAffiliateMerchant: 'от мерчанта',
    pricingAffiliateCreator: 'от автора',
    pricingViewAll: 'Смотреть все тарифы',
    ctaTitle: 'Готов\nначать?',
    ctaBody: 'Хочешь создать магазин или зарабатывать как автор — присоединяйся к NipNip уже сегодня.',
    ctaFree: 'Зарегистрироваться бесплатно',
  },
  common: {
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть',
    loading: 'Загрузка…',
    submitting: 'Отправка…',
    error: 'Произошла ошибка. Попробуйте снова.',
    clear: 'Очистить',
    copy: 'Копировать',
    copied: 'Скопировано!',
    prev: 'Назад',
    next: 'Далее',
    records: 'записей',
    total: 'Всего',
  },
  sidebar: {
    creatorBadge: 'Автор',
    merchantBadge: 'Магазин',
    dashboard: 'Панель',
    myLinks: 'Мои ссылки',
    linkTree: 'Линк-дерево',
    earnings: 'Доходы',
    payouts: 'Выплаты',
    conversions: 'Конверсии',
    reportSale: 'Добавить продажу',
    store: 'Магазин',
    settings: 'Настройки',
    browseMarketplace: 'Все магазины',
    marketplace: 'Маркетплейс',
    integration: 'Интеграция',
    creatorAccess: 'Доступ авторов',
    affiliateGroup: 'Партнёрский маркетинг',
    onlineStoreGroup: 'Интернет-магазин',
    aiAgentsGroup: 'AI-агенты',
    messagingAgent: 'Агент сообщений',
    mediaToolsGroup: 'Медиа-инструменты',
    backgroundRemover: 'Удаление фона',
    socialPostCreator: 'Создание постов',
    aiProductPhotos: 'AI-фото товаров',
    storeOverview: 'Детали',
    storeAnalytics: 'Аналитика',
    storeOrders: 'Заказы',
    storeCategories: 'Категории',
    storeCollections: 'Коллекции',
    storeBundles: 'Наборы',
    storeDiscountCodes: 'Промокоды',
    storePages: 'Страницы',
    storeDesign: 'Дизайн',
    storeLayout: 'Макет',
    storeProducts: 'Товары',
    storeMessages: 'Сообщения',
    storeContact: 'Контакты и соцсети',
    storePayments: 'Оплата',
    storeDelivery: 'Доставка',
    storeDomain: 'Домен',
    storeIntegrations: 'Интеграции',
    navGroupOverview: 'Обзор',
    navGroupDesign: 'Дизайн',
    navGroupProducts: 'Товары',
    navGroupOrders: 'Заказы',
    navGroupPromotions: 'Акции',
    navGroupSettings: 'Настройки',
  },
  admin: {
    badge: 'Admin',
    overview: 'Обзор',
    merchants: 'Магазины',
    creators: 'Авторы',
    conversions: 'Конверсии',
    payouts: 'Выплаты',
    prospects: 'Проспекты',
    websiteInquiries: 'Заявки на сайт',
    demoLogin: 'Демо вход',
    notAuthorized: 'У вас нет доступа к этой странице.',
    goHome: 'На главную',
  },
  creatorDashboard: {
    title: 'Панель',
    subtitle: 'Твоя статистика и доходы',
    clicks: 'Клики',
    conversions: 'Конверсии',
    earnings: 'Доход',
    topMerchants: 'Топ магазины',
    noMerchants: 'Активных магазинов пока нет',
    noMerchantsHint: 'Перейди в «Мои ссылки», чтобы получить ссылки',
    statsError: 'Не удалось загрузить статистику.',
    tableNum: '#',
    tableMerchant: 'Магазин',
    tableClicks: 'Клики',
    tableConversions: 'Конверсии',
    tableCommission: 'Комиссия',
    days7: '7 дней',
    days30: '30 дней',
    days90: '90 дней',
  },
  merchantDashboard: {
    title: 'Панель',
    subtitle: 'Твоя статистика и баланс',
    clicks: 'Клики',
    conversions: 'Конверсии',
    commissionPaid: 'Выплачено комиссий',
    balance: 'Текущий баланс',
    topCreators: 'Топ авторы',
    noCreators: 'Активных авторов пока нет',
    noCreatorsHint: 'Авторы могут найти твою реферальную ссылку',
    statsError: 'Не удалось загрузить статистику.',
    tableNum: '#',
    tableCreator: 'Автор',
    tableClicks: 'Клики',
    tableConversions: 'Конверсии',
    tableCommission: 'Комиссия',
    days7: '7 дней',
    days30: '30 дней',
    days90: '90 дней',
  },
  storeAnalytics: {
    title: 'Аналитика',
    subtitle: 'Трафик и конверсии твоего магазина.',
    visits: 'Визиты',
    pageViews: 'Просмотры страниц',
    productViews: 'Просмотры товаров',
    orders: 'Заказы',
    statsError: 'Не удалось загрузить аналитику.',
    funnelTitle: 'Воронка',
    funnelVisits: 'Визиты',
    funnelProductViews: 'Просмотрел товар',
    funnelOrders: 'Заказал',
    topPagesTitle: 'Популярные страницы',
    noTopPages: 'За этот период просмотров ещё нет.',
    tablePath: 'Страница',
    tableViews: 'Просмотры',
    sourcesTitle: 'Источники трафика',
    noSources: 'За этот период трафика ещё нет.',
    tableSource: 'Источник',
    tableVisits: 'Визиты',
    direct: 'Прямой',
  },
  myLinks: {
    title: 'Мои ссылки',
    subtitle: 'Магазин → кнопка → ссылка. Поделись.',
    featuredBrands: '✦ Избранные бренды',
    allBrands: 'Все бренды',
    getLink: 'Получить ссылку',
    commission: '% комиссия',
    loadError: 'Не удалось загрузить магазины.',
    noMerchants: 'Магазины не найдены',
    trackingLinkLabel: 'Твоя реферальная ссылка',
    modalHint: 'Поделись этой ссылкой с подписчиками. Каждая продажа через эту ссылку засчитывается как твоя комиссия.',
    privateLabel: 'Приватный',
    requestAccess: 'Запросить доступ',
    requestAgain: 'Запросить снова',
    requestPending: 'Запрос отправлен',
  },
  linkTree: {
    title: 'Линк-дерево',
    subtitle: 'Одна ссылка для био — все магазины, которые ты продвигаешь, в одном месте.',
    yourLink: 'Твоя ссылка',
    viewLive: 'Открыть',
    addMerchant: 'Добавить магазин',
    selectMerchant: 'Выбери магазин…',
    labelPlaceholder: 'Своя подпись (необязательно)',
    addButton: 'Добавить',
    addError: 'Не удалось добавить магазин.',
    allAdded: 'Все твои магазины уже добавлены в линк-дерево.',
    empty: 'Твоё линк-дерево пусто. Добавь магазин выше, чтобы начать.',
    remove: 'Удалить',
    moveUp: 'Переместить вверх',
    moveDown: 'Переместить вниз',
    editLabel: 'Изменить подпись',
    loadError: 'Не удалось загрузить твоё линк-дерево.',
    newTree: 'Новое линк-дерево',
    treeNamePlaceholder: 'Название (напр. Летняя подборка)',
    create: 'Создать',
    createError: 'Не удалось создать линк-дерево.',
    defaultBadge: 'По умолчанию',
    setDefault: 'Сделать основным',
    deleteTree: 'Удалить дерево',
    deleteTreeConfirm: 'Удалить это линк-дерево? Это удалит и все его элементы.',
  },
  creatorAccess: {
    title: 'Доступ авторов',
    subtitle: 'Контролируй, кто может тебя продвигать — публичный означает, что любой автор может взять ссылку, приватный — только те, кого ты одобришь.',
    publicLabel: 'Публичный',
    privateLabel: 'Приватный',
    publicHint: 'Любой автор может получить реферальную ссылку и продвигать тебя.',
    privateHint: 'Только одобренные ниже авторы могут получить реферальную ссылку.',
    addCreator: 'Одобрить автора',
    selectCreator: 'Выбери автора…',
    addButton: 'Одобрить',
    addError: 'Не удалось одобрить автора.',
    empty: 'Пока нет запросов.',
    remove: 'Удалить',
    loadError: 'Не удалось загрузить одобренных авторов.',
    pendingSection: 'Ожидающие запросы',
    approvedSection: 'Одобренные',
    rejectedSection: 'Отклонённые',
    approve: 'Одобрить',
    reject: 'Отклонить',
  },
  backgroundRemover: {
    subtitle: 'Загрузи фото товара и получи чистую версию с прозрачным фоном — отлично подходит для постов.',
    uploadPrompt: 'Нажми, чтобы загрузить фото',
    uploadError: 'Не удалось загрузить. Попробуй снова.',
    original: 'Оригинал',
    bgRemoved: 'Без фона',
    download: 'Скачать',
  },
  socialPostCreator: {
    subtitle: 'Загрузи фото товара и получи готовые посты нужного размера для каждой платформы.',
    uploadPrompt: 'Нажми, чтобы загрузить фото',
    uploadError: 'Не удалось загрузить. Попробуй снова.',
    removingBackground: 'Удаляем фон…',
    backgroundLabel: 'Фон',
    platformLabel: 'Размер платформы',
    solid: 'Один цвет',
    pattern: 'Узор',
    customColor: 'Свой цвет',
    patternDots: 'Точки',
    patternStripes: 'Полосы',
    patternGrid: 'Сетка',
    patternCheckerboard: 'Шахматка',
    patternWaves: 'Волны',
    download: 'Скачать',
    layoutCentered: 'По центру',
    layoutRotated: 'Повёрнуто',
    layoutBottomCrop: 'Крупный план',
    platformFacebook: 'Пост Facebook',
    platformInstagramPost: 'Пост Instagram',
    platformInstagramStory: 'История Instagram',
    platformTiktok: 'TikTok',
    platformProductPage: 'Страница товара',
    dragHint: 'Перетащи, чтобы переместить',
    sizeLabel: 'Размер',
    rotateLabel: 'Поворот',
    priceLabel: 'Бейдж цены',
    pricePlaceholder: 'напр. 29.99 ₾',
    logoLabel: 'Логотип магазина',
    noLogo: 'Добавь логотип в настройках магазина, чтобы использовать это',
    resetPosition: 'Сбросить позицию',
    createProductTitle: 'Готов продавать?',
    createProductSubtitle: 'Создай товар, используя эти 3 изображения как галерею.',
    createProduct: 'Создать товар с этими изображениями',
    createProductError: 'Не удалось создать товар из этих изображений. Попробуй снова.',
    postToTiktokTitle: 'Опубликовать это в TikTok?',
    postToTiktokSubtitle: 'Выбери макет, добавь подпись и опубликуй в подключённый аккаунт TikTok.',
    postToTiktokLayoutLabel: 'Макет',
    postToTiktokLayoutHint: 'Выбери один или несколько — нажми ещё раз, чтобы убрать. Публикуются в том порядке, в котором выбраны.',
    postToTiktokAutoMusic: 'Разрешить TikTok добавить рекомендованную музыку',
    postToTiktokAutoMusicHint: 'API TikTok не позволяет выбрать конкретный трек — это просто разрешает TikTok автоматически добавить один из своих вариантов, который автор всё ещё может сменить в самом приложении.',
    postToTiktokTitleLabel: 'Заголовок',
    postToTiktokDescLabel: 'Описание',
    postToTiktokButton: 'Опубликовать в TikTok',
    postToTiktokNotConnected: 'Подключи TikTok в разделе Интеграции, чтобы публиковать отсюда напрямую.',
    postToTiktokConnectLink: 'Перейти в Интеграции',
    postToTiktokError: 'Не удалось опубликовать в TikTok. Попробуй снова.',
    postToTiktokSuccessPrefix: 'Опубликовано в TikTok — видимость:',
    postToTiktokAuditNote: 'Твоё приложение ещё не прошло проверку TikTok, поэтому первые публикации видны только тебе.',
  },
  aiProductPhotos: {
    subtitle: 'Дай AI фото своего товара и опиши, что хочешь получить — лайфстайл-фото, товар на модели, новый фон — что угодно.',
    referenceLabel: 'Референс-фото (до 3)',
    uploadPrompt: 'Нажми, чтобы загрузить фото',
    uploadError: 'Не удалось загрузить. Попробуй снова.',
    sceneLabel: 'Сцена',
    sceneStudio: 'Студия (белый фон)',
    sceneOutdoorPark: 'На улице / парк',
    sceneUrbanStreet: 'Городская улица',
    sceneBeach: 'Пляж',
    sceneIndoorLifestyle: 'Домашний интерьер',
    sceneFlatLay: 'Плоская раскладка (без модели)',
    subjectLabel: 'Субъект',
    subjectModelFemale: 'Модель — женщина',
    subjectModelMale: 'Модель — мужчина',
    subjectNoModel: 'Только товар',
    lightingLabel: 'Освещение',
    lightingBrightClean: 'Яркое и чистое',
    lightingGoldenHour: 'Закатный час',
    lightingMoody: 'Драматичное',
    lightingSoftNatural: 'Мягкое естественное',
    detailsLabel: 'Дополнительные детали (необязательно)',
    detailsPlaceholder: 'напр. добавь маленькую собаку рядом с моделью, фон более размытым...',
    promptPreviewLabel: 'Промпт, который будет отправлен',
    generate: 'Сгенерировать',
    generating: 'Генерируем…',
    generateError: 'Не удалось сгенерировать изображение. Попробуй снова.',
    usageLabel: 'AI-генераций в этом месяце',
    quotaExceeded: 'Ты использовал все AI-генерации в этом месяце. Обновится 1-го числа.',
    resultsTitle: 'Сгенерированные фото',
    download: 'Скачать',
  },
  earnings: {
    title: 'Доходы',
    subtitle: 'История твоих комиссий',
    history: 'История доходов',
    noEarnings: 'Комиссий пока нет',
    noEarningsHint: 'Распространи ссылки и продажи появятся здесь',
    loadError: 'Не удалось загрузить данные.',
    colDate: 'Дата',
    colMerchant: 'Магазин',
    colOrder: 'Заказ',
    colCommission: 'Ваш доход',
    colSource: 'Источник',
    colStatus: 'Статус',
    allTime: 'Всё время',
    monthlySales: 'продаж',
    monthlyEarned: 'заработано',
    monthlyBreakdown: 'По месяцам',
  },
  conversionsPage: {
    title: 'Конверсии',
    subtitle: 'Все конверсии от авторов',
    history: 'История конверсий',
    noConversions: 'Конверсий пока нет',
    noConversionsHint: 'Авторы распространят ссылки и продажи появятся',
    loadError: 'Не удалось загрузить данные.',
    colDate: 'Дата',
    colCreator: 'Автор',
    colOrder: 'Заказ',
    colCommission: 'К оплате',
    colSource: 'Источник',
    colStatus: 'Статус',
    allTime: 'Всё время',
    monthlySales: 'продаж',
    monthlyOwed: 'итого к оплате',
    monthlyBreakdown: 'По месяцам',
  },
  status: {
    Pending: 'Ожидает',
    Confirmed: 'Подтверждено',
    Rejected: 'Отклонено',
    Paid: 'Выплачено',
  },
  source: {
    ManualReport: 'Вручную',
    JsSnippet: 'JS',
    WooCommercePlugin: 'WooC.',
    Api: 'API',
  },
  merchantsPage: {
    badge: '⬡ Бренды',
    title: 'Магазины-партнёры',
    subtitle: 'Выбери бренд, получи ссылку и код, поделись — зарабатывай.',
    featuredBrands: '✦ Избранные бренды',
    allShops: 'Все магазины',
    noShops: 'Магазинов пока нет.',
    websiteLink: 'Сайт ↗',
    getLink: 'Получить ссылку →',
    getLinkBtn: 'Получить ссылку',
    forBrand: 'Твоя ссылка для этого бренда',
    trackingLinkLabel: 'Твоя реферальная ссылка',
    modalHint: 'Поделись этой ссылкой с подписчиками. Каждая продажа через эту ссылку засчитывается как твоя комиссия.',
    viewProfile: 'Профиль',
    commissionRate: 'Ставка комиссии',
    partnerSince: 'Партнёр с',
    noDescription: 'Нет описания',
  },
  reportSale: {
    title: 'Добавить продажу',
    subtitle: 'Ручное добавление конверсии',
    creatorLabel: 'Автор (slug или имя)',
    creatorPlaceholder: 'напр. giorgi123',
    amountLabel: 'Сумма заказа',
    amountPlaceholder: 'напр. 49.99',
    currencyLabel: 'Валюта',
    orderIdLabel: 'ID заказа (необязательно)',
    orderIdPlaceholder: 'напр. ORD-1234',
    submit: 'Добавить конверсию',
    submitting: 'Добавляется…',
    success: 'Конверсия успешно добавлена!',
    error: 'Не удалось добавить конверсию.',
  },
  onboarding: {
    heroHeadline: 'NipNip — запустите магазин за 15 минут',
    heroSubheadline: 'Оставьте контакт, и наша команда позвонит вам сегодня же — мы полностью соберём ваш интернет-магазин за вас.',
    benefit1: '⚡ Готово за 15 минут',
    benefit2: '🎁 Полностью бесплатно',
    benefit3: '🤝 Персональная поддержка с первого дня',
    title: 'Начните прямо сейчас',
    subtitle: 'Всего 2 коротких шага.',
    step1Label: 'Шаг 1/2',
    step2Label: 'Шаг 2/2',
    nameLabel: 'Имя',
    namePlaceholder: 'напр. Giorgi Lomidze',
    storeNameLabel: 'Название магазина',
    storeNamePlaceholder: 'напр. GL Store',
    storeNameHint: 'Ещё не знаете? Ничего страшного — пропустите.',
    emailLabel: 'Эл. почта',
    emailPlaceholder: 'name@example.com',
    phoneLabel: 'Номер телефона',
    phonePlaceholder: '+995 5xx xx xx xx',
    contactHint: 'Укажите эл. почту или номер телефона',
    next: 'Далее',
    back: 'Назад',
    submit: 'Отправить',
    submitting: 'Отправка…',
    errorName: 'Имя обязательно.',
    errorContact: 'Укажите эл. почту или номер телефона.',
    errorEmail: 'Неверный формат эл. почты.',
    error: 'Произошла ошибка. Попробуйте снова.',
    successTitle: 'Спасибо!',
    successBody: 'Команда NipNip скоро свяжется с вами.',
    meanwhileTitle: 'Тем временем',
    meanwhileBody: 'Если вас что-то интересует, напишите нам в Facebook или Instagram:',
  },
  settings: {
    title: 'Настройки',
    profileSection: 'Профиль',
    socialSection: 'Социальные сети',
    notificationsSection: 'Уведомления',
    nameLabel: 'Имя',
    slugLabel: 'Slug',
    instagramLabel: 'Instagram',
    tiktokLabel: 'TikTok',
    youtubeLabel: 'YouTube',
    facebookLabel: 'Facebook',
    xLabel: 'X (Twitter)',
    linkedinLabel: 'LinkedIn',
    followersLabel: 'Подписчики',
    websiteLabel: 'Сайт',
    descriptionLabel: 'Описание',
    logoLabel: 'URL логотипа',
    commissionLabel: 'Комиссия %',
    notificationEmailLabel: 'Email для уведомлений',
    notificationEmailHint: 'На этот адрес будет приходить письмо о каждой новой продаже',
    saveSuccess: 'Изменения сохранены!',
    saveError: 'Не удалось сохранить.',
    avatarSection: 'Фото профиля',
    uploadPhoto: 'Загрузить фото',
    uploadHint: 'JPG, PNG, WEBP · макс. 5 МБ',
    uploading: 'Загрузка…',
    uploadError: 'Ошибка загрузки.',
    optional: '(необязательно)',
    followersPlaceholder: 'Подписчики',
    clickToSelect: 'PNG, JPG, WEBP · нажми для выбора',
    readOnly: '(нельзя изменить)',
    profileSubtitle: 'Редактировать профиль',
  },
  creatorsPage: {
    badge: '◉ Авторы',
    title: 'Наши авторы',
    subtitle: 'Талантливые люди, которые продвигают бренды через NipNip и зарабатывают комиссии.',
    featuredCreators: '✦ Избранные авторы',
    allCreators: 'Все авторы',
    noCreators: 'Авторов пока нет.',
    viewProfile: 'Профиль',
    noSocials: 'Соцсетей нет',
    memberSince: 'Участник с',
    socials: 'Социальные сети',
  },
  carousel: {
    trackingLinkLabel: 'Твоя реферальная ссылка',
    forBrand: 'Твоя ссылка для этого бренда',
    modalHint: 'Поделись этой ссылкой с подписчиками. Каждая продажа через эту ссылку засчитывается как твоя комиссия.',
    getLink: 'Получить ссылку →',
  },
  signInRequired: {
    title: 'Требуется авторизация',
    body: 'Войдите в аккаунт, чтобы получить реферальную ссылку.',
    cta: 'Войти',
  },
  detail: {
    title: 'Детали конверсии',
    notFound: 'Конверсия не найдена.',
    statusLabel: 'Статус',
    yourCommission: 'Ваш доход',
    commission: 'К оплате',
    saleAmount: 'Сумма продажи',
    merchant: 'Магазин',
    creator: 'Автор',
    orderId: 'ID заказа',
    sourceLabel: 'Источник',
    backEarnings: 'Доходы',
    backConversions: 'Конверсии',
  },
  sourceFull: {
    ManualReport: 'Ручной ввод',
    JsSnippet: 'JS Snippet',
    WooCommercePlugin: 'WooCommerce',
    Api: 'API',
  },
  integration: {
    title: 'Интеграция сайта',
    subtitle: 'Запусти трекинг NipNip на своём сайте.',
    platformSelector: 'Выбери платформу',
    platformWoo: 'WooCommerce',
    platformCustom: 'Custom Website',
    wooApiKeyTitle: 'API Ключ',
    wooApiKeyDesc: 'Введи этот ключ в настройках плагина.',
    wooDownloadBtn: 'Скачать плагин',
    wooComingSoon: 'Скоро будет доступен.',
    wooStep1: '1. Скачать плагин',
    wooStep1Desc: 'Скачай плагин NipNip WooCommerce по кнопке ниже.',
    wooStep2: '2. Установить в WordPress',
    wooStep2Desc: 'WordPress Admin → Plugins → Add New → Upload Plugin → загрузи .zip → Install Now → Activate.',
    wooStep3: '3. Ввести API-ключ',
    wooStep3Desc: 'В настройках плагина (WooCommerce → NipNip Settings) вставь API-ключ из блока выше.',
    wooDone: '4. Готово!',
    wooDoneDesc: 'Трекинг полностью автоматический — NipNip фиксирует каждый заказ автоматически.',
    snippet1Label: 'Сниппет 1 — Глобальный шаблон',
    snippet1Desc: 'Вставь один раз в общий footer или HTML-шаблон сайта. Сохраняет NipNip ref в cookie браузера посетителя.',
    snippet2Label: 'Сниппет 2 — Страница подтверждения',
    snippet2Desc: 'Вставь только на страницу подтверждения заказа (thank you page).',
    cookieNote: 'Cookie _nn_ref запоминает, какой автор привёл этого посетителя — сниппет читает его автоматически.',
    examplesTitle: 'Подставить ORDER_ID и AMOUNT',
    examplesDesc: 'Замени ORDER_ID и AMOUNT реальными значениями из твоего бэкенда.',
    phpTab: 'PHP',
    jsTab: 'JavaScript',
    copySnippet: 'Скопировать',
    copied: 'Скопировано!',
    testBtn: 'Проверить подключение',
    testing: 'Проверка…',
    connectedBadge: 'Подключено',
    notConnectedBadge: 'Нет подключения',
    testHint: 'Проверь, что API-ключ валиден и сервер доступен.',
    connectedHint: 'API-ключ валиден. Подключение успешно.',
    notConnectedHint: 'Подключение не удалось. Проверь API-ключ.',
    loadError: 'Не удалось загрузить сниппеты.',
    noWebsiteNote: 'Нет сайта? Можно добавлять продажи вручную из Dashboard',
    noWebsiteLink: 'Добавить продажу вручную →',
    platformShopify: 'Shopify',
    shopifyStep1Label: 'Шаг 1 — theme.liquid (перед </head>)',
    shopifyStep1Desc: 'Online Store (левая панель) → 3 точки на активной теме → Edit code → папка Layout → theme.liquid → вставь перед </head>.',
    shopifyStep2Label: 'Шаг 2 — Custom Pixel (Customer Events)',
    shopifyStep2Desc: 'Settings → Customer events → Custom pixels → Add custom pixel → назови Nipnip Webhook → вставь код → Add pixel.',
    shopifyLiquidNote: 'checkout.order.id, checkout.totalPrice.amount и checkout.totalPrice.currencyCode — поля Shopify Customer Events API, они автоматически заполняются данными заказа.',
    platformStore: 'Магазин NipNip',
    storeTabTitle: 'Твой магазин NipNip',
    storeTabDesc: 'Устанавливать код не нужно — раз твой магазин уже на NipNip, трекинг встроен. Просто включи переключатель.',
    storeToggleLabel: 'Партнёрский трекинг',
    storeToggleOnDesc: 'Включено — ссылки авторов ведут прямо в твой магазин, и каждый завершённый заказ отслеживается и засчитывается автоматически.',
    storeToggleOffDesc: 'Выключено — ссылки авторов не будут отслеживать продажи в твоём магазине NipNip.',
    storeNoStoreNote: 'У тебя ещё нет магазина NipNip.',
    storeNoStoreLink: 'Создать магазин →',
  },
}
