import type { Strings } from './ka'

export const ru: Strings = {
  nav: {
    brands: 'Бренды',
    creators: 'Авторы',
    howItWorks: 'Как это работает',
    faq: 'FAQ',
    signIn: 'Войти',
    signUp: 'Регистрация',
    dashboard: 'Панель',
  },
  footer: {
    tagline: 'Грузинская affiliate-платформа для авторов и магазинов.',
    platform: 'Платформа',
    forCreators: 'Авторам',
    forMerchants: 'Магазинам',
    copyright: 'Создано для авторов',
    about: 'О нас',
    howItWorks: 'Как это работает',
    faq: 'FAQ',
    contact: 'Контакт',
    signUp: 'Регистрация',
    merchants: 'Магазины',
    creatorDashboard: 'Панель автора',
    joinAsMerchant: 'Присоединиться',
    merchantDashboard: 'Панель магазина',
    poweredBy: 'powered by',
  },
  landing: {
    badge: 'Affiliate-платформа для авторов',
    headline1: 'Поделись ссылкой.',
    headline2: 'Получи комиссию.',
    tagline: 'NipNip связывает авторов с магазинами. Получи свой код, продавай и отслеживай доход — всё в одном месте.',
    ctaSignUp: 'Зарегистрироваться как автор',
    ctaHowItWorks: 'Как это работает',
    featuredBrandsLabel: '✦ Избранные бренды',
    partnerShops: 'Магазины-партнёры',
    viewAll: 'Смотреть все',
    howItWorksBadge: 'Как это работает',
    howItWorksTitle: 'Три шага',
    howItWorksAccent: 'до первой комиссии.',
    step1Title: 'Зарегистрируйся',
    step1Body: 'Открой бесплатный аккаунт за несколько секунд. Карта не нужна.',
    step2Title: 'Получи ссылку',
    step2Body: 'Получи уникальный промокод или реферальную ссылку для любого магазина-партнёра.',
    step3Title: 'Зарабатывай',
    step3Body: 'Каждая продажа — это комиссия. Доход виден в аккаунте в реальном времени.',
    ctaTitle: 'Готов\nначать?',
    ctaBody: 'Присоединяйся к авторам, которые уже работают с NipNip и зарабатывают каждый день.',
    ctaFree: 'Зарегистрироваться бесплатно',
  },
  common: {
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть',
    loading: 'Загрузка…',
    submitting: 'Отправка…',
    error: 'Произошла ошибка. Попробуйте снова.',
    clear: 'Очистить',
    copy: 'Копировать',
    copied: 'Скопировано!',
    prev: 'Назад',
    next: 'Далее',
    records: 'записей',
    total: 'Всего',
  },
  sidebar: {
    creatorBadge: 'Автор',
    merchantBadge: 'Магазин',
    dashboard: 'Панель',
    myLinks: 'Мои ссылки',
    earnings: 'Доходы',
    payouts: 'Выплаты',
    conversions: 'Конверсии',
    reportSale: 'Добавить продажу',
    store: 'Магазин',
    settings: 'Настройки',
    browseMarketplace: 'Все магазины',
    marketplace: 'Маркетплейс',
    integration: 'Интеграция',
    affiliateGroup: 'Партнёрский маркетинг',
    onlineStoreGroup: 'Интернет-магазин',
    storeOverview: 'Детали',
    storeOrders: 'Заказы',
    storeCategories: 'Категории',
    storePages: 'Страницы',
    storeDesign: 'Дизайн',
    storeProducts: 'Товары',
    storeMessages: 'Сообщения',
    storeContact: 'Контакты и соцсети',
    storePayments: 'Оплата',
    storeDelivery: 'Доставка',
    storeDomain: 'Домен',
  },
  creatorDashboard: {
    title: 'Панель',
    subtitle: 'Твоя статистика и доходы',
    clicks: 'Клики',
    conversions: 'Конверсии',
    earnings: 'Доход',
    topMerchants: 'Топ магазины',
    noMerchants: 'Активных магазинов пока нет',
    noMerchantsHint: 'Перейди в «Мои ссылки», чтобы получить ссылки',
    statsError: 'Не удалось загрузить статистику.',
    tableNum: '#',
    tableMerchant: 'Магазин',
    tableClicks: 'Клики',
    tableConversions: 'Конверсии',
    tableCommission: 'Комиссия',
    days7: '7 дней',
    days30: '30 дней',
    days90: '90 дней',
  },
  merchantDashboard: {
    title: 'Панель',
    subtitle: 'Твоя статистика и баланс',
    clicks: 'Клики',
    conversions: 'Конверсии',
    commissionPaid: 'Выплачено комиссий',
    balance: 'Текущий баланс',
    topCreators: 'Топ авторы',
    noCreators: 'Активных авторов пока нет',
    noCreatorsHint: 'Авторы могут найти твою реферальную ссылку',
    statsError: 'Не удалось загрузить статистику.',
    tableNum: '#',
    tableCreator: 'Автор',
    tableClicks: 'Клики',
    tableConversions: 'Конверсии',
    tableCommission: 'Комиссия',
    days7: '7 дней',
    days30: '30 дней',
    days90: '90 дней',
  },
  myLinks: {
    title: 'Мои ссылки',
    subtitle: 'Магазин → кнопка → ссылка. Поделись.',
    featuredBrands: '✦ Избранные бренды',
    allBrands: 'Все бренды',
    getLink: 'Получить ссылку',
    commission: '% комиссия',
    loadError: 'Не удалось загрузить магазины.',
    noMerchants: 'Магазины не найдены',
    trackingLinkLabel: 'Твоя реферальная ссылка',
    modalHint: 'Поделись этой ссылкой с подписчиками. Каждая продажа через эту ссылку засчитывается как твоя комиссия.',
  },
  earnings: {
    title: 'Доходы',
    subtitle: 'История твоих комиссий',
    history: 'История доходов',
    noEarnings: 'Комиссий пока нет',
    noEarningsHint: 'Распространи ссылки и продажи появятся здесь',
    loadError: 'Не удалось загрузить данные.',
    colDate: 'Дата',
    colMerchant: 'Магазин',
    colOrder: 'Заказ',
    colCommission: 'Ваш доход',
    colSource: 'Источник',
    colStatus: 'Статус',
    allTime: 'Всё время',
    monthlySales: 'продаж',
    monthlyEarned: 'заработано',
    monthlyBreakdown: 'По месяцам',
  },
  conversionsPage: {
    title: 'Конверсии',
    subtitle: 'Все конверсии от авторов',
    history: 'История конверсий',
    noConversions: 'Конверсий пока нет',
    noConversionsHint: 'Авторы распространят ссылки и продажи появятся',
    loadError: 'Не удалось загрузить данные.',
    colDate: 'Дата',
    colCreator: 'Автор',
    colOrder: 'Заказ',
    colCommission: 'К оплате',
    colSource: 'Источник',
    colStatus: 'Статус',
    allTime: 'Всё время',
    monthlySales: 'продаж',
    monthlyOwed: 'итого к оплате',
    monthlyBreakdown: 'По месяцам',
  },
  status: {
    Pending: 'Ожидает',
    Confirmed: 'Подтверждено',
    Rejected: 'Отклонено',
    Paid: 'Выплачено',
  },
  source: {
    ManualReport: 'Вручную',
    JsSnippet: 'JS',
    WooCommercePlugin: 'WooC.',
    Api: 'API',
  },
  merchantsPage: {
    badge: '⬡ Бренды',
    title: 'Магазины-партнёры',
    subtitle: 'Выбери бренд, получи ссылку и код, поделись — зарабатывай.',
    featuredBrands: '✦ Избранные бренды',
    allShops: 'Все магазины',
    noShops: 'Магазинов пока нет.',
    websiteLink: 'Сайт ↗',
    getLink: 'Получить ссылку →',
    getLinkBtn: 'Получить ссылку',
    forBrand: 'Твоя ссылка для этого бренда',
    trackingLinkLabel: 'Твоя реферальная ссылка',
    modalHint: 'Поделись этой ссылкой с подписчиками. Каждая продажа через эту ссылку засчитывается как твоя комиссия.',
    viewProfile: 'Профиль',
    commissionRate: 'Ставка комиссии',
    partnerSince: 'Партнёр с',
    noDescription: 'Нет описания',
  },
  reportSale: {
    title: 'Добавить продажу',
    subtitle: 'Ручное добавление конверсии',
    creatorLabel: 'Автор (slug или имя)',
    creatorPlaceholder: 'напр. giorgi123',
    amountLabel: 'Сумма заказа',
    amountPlaceholder: 'напр. 49.99',
    currencyLabel: 'Валюта',
    orderIdLabel: 'ID заказа (необязательно)',
    orderIdPlaceholder: 'напр. ORD-1234',
    submit: 'Добавить конверсию',
    submitting: 'Добавляется…',
    success: 'Конверсия успешно добавлена!',
    error: 'Не удалось добавить конверсию.',
  },
  onboarding: {
    title: 'Добро пожаловать в NipNip!',
    subtitle: 'Заполни профиль, чтобы начать.',
    nameLabel: 'Имя / название бренда',
    namePlaceholder: 'напр. Giorgi Lomidze',
    slugLabel: 'Slug (твой уникальный URL)',
    slugPlaceholder: 'напр. giorgi',
    slugHint: 'Используется в твоих реферальных ссылках',
    instagramLabel: 'Instagram',
    instagramPlaceholder: '@giorgi',
    tiktokLabel: 'TikTok',
    tiktokPlaceholder: '@giorgi',
    submit: 'Сохранить профиль',
    submitting: 'Сохранение…',
    error: 'Не удалось сохранить профиль.',
  },
  settings: {
    title: 'Настройки',
    profileSection: 'Профиль',
    socialSection: 'Социальные сети',
    notificationsSection: 'Уведомления',
    nameLabel: 'Имя',
    slugLabel: 'Slug',
    instagramLabel: 'Instagram',
    tiktokLabel: 'TikTok',
    youtubeLabel: 'YouTube',
    facebookLabel: 'Facebook',
    xLabel: 'X (Twitter)',
    linkedinLabel: 'LinkedIn',
    followersLabel: 'Подписчики',
    websiteLabel: 'Сайт',
    descriptionLabel: 'Описание',
    logoLabel: 'URL логотипа',
    commissionLabel: 'Комиссия %',
    notificationEmailLabel: 'Email для уведомлений',
    notificationEmailHint: 'На этот адрес будет приходить письмо о каждой новой продаже',
    saveSuccess: 'Изменения сохранены!',
    saveError: 'Не удалось сохранить.',
    avatarSection: 'Фото профиля',
    uploadPhoto: 'Загрузить фото',
    uploadHint: 'JPG, PNG, WEBP · макс. 5 МБ',
    uploading: 'Загрузка…',
    uploadError: 'Ошибка загрузки.',
    optional: '(необязательно)',
    followersPlaceholder: 'Подписчики',
    clickToSelect: 'PNG, JPG, WEBP · нажми для выбора',
    readOnly: '(нельзя изменить)',
    profileSubtitle: 'Редактировать профиль',
  },
  creatorsPage: {
    badge: '◉ Авторы',
    title: 'Наши авторы',
    subtitle: 'Талантливые люди, которые продвигают бренды через NipNip и зарабатывают комиссии.',
    featuredCreators: '✦ Избранные авторы',
    allCreators: 'Все авторы',
    noCreators: 'Авторов пока нет.',
    viewProfile: 'Профиль',
    noSocials: 'Соцсетей нет',
    memberSince: 'Участник с',
    socials: 'Социальные сети',
  },
  carousel: {
    trackingLinkLabel: 'Твоя реферальная ссылка',
    forBrand: 'Твоя ссылка для этого бренда',
    modalHint: 'Поделись этой ссылкой с подписчиками. Каждая продажа через эту ссылку засчитывается как твоя комиссия.',
    getLink: 'Получить ссылку →',
  },
  signInRequired: {
    title: 'Требуется авторизация',
    body: 'Войдите в аккаунт, чтобы получить реферальную ссылку.',
    cta: 'Войти',
  },
  detail: {
    title: 'Детали конверсии',
    notFound: 'Конверсия не найдена.',
    statusLabel: 'Статус',
    yourCommission: 'Ваш доход',
    commission: 'К оплате',
    saleAmount: 'Сумма продажи',
    merchant: 'Магазин',
    creator: 'Автор',
    orderId: 'ID заказа',
    sourceLabel: 'Источник',
    backEarnings: 'Доходы',
    backConversions: 'Конверсии',
  },
  sourceFull: {
    ManualReport: 'Ручной ввод',
    JsSnippet: 'JS Snippet',
    WooCommercePlugin: 'WooCommerce',
    Api: 'API',
  },
  integration: {
    title: 'Интеграция сайта',
    subtitle: 'Запусти трекинг NipNip на своём сайте.',
    platformSelector: 'Выбери платформу',
    platformWoo: 'WooCommerce',
    platformCustom: 'Custom Website',
    wooApiKeyTitle: 'API Ключ',
    wooApiKeyDesc: 'Введи этот ключ в настройках плагина.',
    wooDownloadBtn: 'Скачать плагин',
    wooComingSoon: 'Скоро будет доступен.',
    wooStep1: '1. Скачать плагин',
    wooStep1Desc: 'Скачай плагин NipNip WooCommerce по кнопке ниже.',
    wooStep2: '2. Установить в WordPress',
    wooStep2Desc: 'WordPress Admin → Plugins → Add New → Upload Plugin → загрузи .zip → Install Now → Activate.',
    wooStep3: '3. Ввести API-ключ',
    wooStep3Desc: 'В настройках плагина (WooCommerce → NipNip Settings) вставь API-ключ из блока выше.',
    wooDone: '4. Готово!',
    wooDoneDesc: 'Трекинг полностью автоматический — NipNip фиксирует каждый заказ автоматически.',
    snippet1Label: 'Сниппет 1 — Глобальный шаблон',
    snippet1Desc: 'Вставь один раз в общий footer или HTML-шаблон сайта. Сохраняет NipNip ref в cookie браузера посетителя.',
    snippet2Label: 'Сниппет 2 — Страница подтверждения',
    snippet2Desc: 'Вставь только на страницу подтверждения заказа (thank you page).',
    cookieNote: 'Cookie _nn_ref запоминает, какой автор привёл этого посетителя — сниппет читает его автоматически.',
    examplesTitle: 'Подставить ORDER_ID и AMOUNT',
    examplesDesc: 'Замени ORDER_ID и AMOUNT реальными значениями из твоего бэкенда.',
    phpTab: 'PHP',
    jsTab: 'JavaScript',
    copySnippet: 'Скопировать',
    copied: 'Скопировано!',
    testBtn: 'Проверить подключение',
    testing: 'Проверка…',
    connectedBadge: 'Подключено',
    notConnectedBadge: 'Нет подключения',
    testHint: 'Проверь, что API-ключ валиден и сервер доступен.',
    connectedHint: 'API-ключ валиден. Подключение успешно.',
    notConnectedHint: 'Подключение не удалось. Проверь API-ключ.',
    loadError: 'Не удалось загрузить сниппеты.',
    noWebsiteNote: 'Нет сайта? Можно добавлять продажи вручную из Dashboard',
    noWebsiteLink: 'Добавить продажу вручную →',
    platformShopify: 'Shopify',
    shopifyStep1Label: 'Шаг 1 — theme.liquid (перед </head>)',
    shopifyStep1Desc: 'Online Store (левая панель) → 3 точки на активной теме → Edit code → папка Layout → theme.liquid → вставь перед </head>.',
    shopifyStep2Label: 'Шаг 2 — Custom Pixel (Customer Events)',
    shopifyStep2Desc: 'Settings → Customer events → Custom pixels → Add custom pixel → назови Nipnip Webhook → вставь код → Add pixel.',
    shopifyLiquidNote: 'checkout.order.id, checkout.totalPrice.amount и checkout.totalPrice.currencyCode — поля Shopify Customer Events API, они автоматически заполняются данными заказа.',
    platformStore: 'Магазин NipNip',
    storeTabTitle: 'Твой магазин NipNip',
    storeTabDesc: 'Устанавливать код не нужно — раз твой магазин уже на NipNip, трекинг встроен. Просто включи переключатель.',
    storeToggleLabel: 'Партнёрский трекинг',
    storeToggleOnDesc: 'Включено — ссылки авторов ведут прямо в твой магазин, и каждый завершённый заказ отслеживается и засчитывается автоматически.',
    storeToggleOffDesc: 'Выключено — ссылки авторов не будут отслеживать продажи в твоём магазине NipNip.',
    storeNoStoreNote: 'У тебя ещё нет магазина NipNip.',
    storeNoStoreLink: 'Создать магазин →',
  },
}
