import type { StorefrontStrings } from './storefront-ka'

export const ru: StorefrontStrings = {
  header: {
    allProducts: 'Все товары',
    categories: 'Категории',
    cart: 'Корзина',
    menuAriaLabel: 'Меню',
    closeAriaLabel: 'Закрыть',
    searchAriaLabel: 'Поиск',
  },
  footer: {
    poweredBy: 'Работает на NipNip',
  },
  home: {
    heroPrimaryCta: 'Смотреть все товары',
    heroSecondaryCta: 'Узнать больше',
    allProductsHeading: 'Все товары',
    viewAll: 'Смотреть все →',
    noProductsYet: 'Товаров пока нет.',
    slideAriaLabel: (n: number) => `Слайд ${n}`,
    scrollLeftAriaLabel: 'Прокрутить влево',
    scrollRightAriaLabel: 'Прокрутить вправо',
    emptyRowMessage: 'Пока ничего не добавлено.',
  },
  product: {
    noImage: 'Нет изображения',
    lowStock: (n: number) => `Осталось всего ${n} шт.!`,
    inStock: (n: number) => `В наличии: ${n} шт.`,
    outOfStock: 'Нет в наличии',
    addedToCart: '✓ Добавлено в корзину',
    chooseVariant: 'Выберите вариант',
    addToCart: 'Добавить в корзину',
    addToCartError: 'Произошла ошибка. Попробуйте снова.',
    description: 'Описание',
    video: 'Видео',
    relatedProducts: 'Похожие товары',
    sizeGuide: 'Таблица размеров',
    zoomAriaLabel: 'Увеличить изображение',
    breadcrumbHome: 'Главная',
    breadcrumbAllProducts: 'Все товары',
    saleBadge: 'Скидка',
  },
  grid: {
    collectionEyebrow: 'Коллекция',
    allProductsTitle: 'Все товары',
    allCategoriesLink: 'Все',
    unitProduct: 'товаров',
    searchPlaceholder: 'Поиск...',
    noProductsFound: 'Товары не найдены.',
    priceLabel: 'Цена',
    minPriceAriaLabel: 'Ползунок минимальной цены',
    maxPriceAriaLabel: 'Ползунок максимальной цены',
    sortFeatured: 'Рекомендуемые',
    sortPriceAsc: 'Цена: по возрастанию',
    sortPriceDesc: 'Цена: по убыванию',
    sortNameAsc: 'Название: А-Я',
    sortNameDesc: 'Название: Я-А',
  },
  cart: {
    loading: 'Загрузка...',
    emptyHeading: 'Ваша корзина пуста',
    emptySubtext: 'Просмотрите каталог и выберите то, что вам нравится.',
    continueShopping: 'Продолжить покупки',
    heading: 'Ваша корзина',
    itemCount: (n: number) => `${n} товар(ов)`,
    bundleTag: '(набор)',
    removeBundleAriaLabel: 'Удалить набор',
    removeItemAriaLabel: 'Удалить товар',
    outOfStock: 'Нет в наличии',
    onlyXInStock: (stock: number) => `В наличии только ${stock} шт.`,
    continueShoppingBack: '← Продолжить покупки',
    orderSummary: 'Итоги заказа',
    total: 'Итого',
    freeShippingNudge: (amount: string) => `Добавьте ещё ₾${amount} для бесплатной доставки`,
    checkoutCta: 'Перейти к оформлению',
    reduceQuantityMessage: 'Уменьшите количество до доступного в наличии, чтобы продолжить.',
    noImage: 'Нет изображения',
    addedToast: 'Товар добавлен в корзину',
    bundleAddedToast: 'Набор добавлен в корзину',
  },
  checkout: {
    paymentMethods: {
      cashOnDelivery: 'Оплата при доставке',
      bankTransfer: 'Банковский перевод',
      flitt: 'Оплата картой',
      tbc: 'Оплата картой (TBC)',
      bog: 'Оплата картой (Bank of Georgia)',
      cityPay: 'Оплата криптовалютой',
    },
    discountErrors: {
      notFound: 'Неверный код.',
      inactive: 'Код больше не активен.',
      expired: 'Срок действия кода истёк.',
      maxUses: 'Код больше недоступен.',
    },
    minOrderDiscountError: (amount: string) => `Минимальная сумма заказа для этого кода: ₾${amount}`,
    redirecting: 'Перенаправление на защищённую страницу оплаты...',
    thankYouHeading: 'Заказ оформлен!',
    thankYouMessage: (name: string, orderId: string, email: string) =>
      `Спасибо, ${name}. Ваш заказ #${orderId} принят. Детали отправлены на ${email}.`,
    orderTotal: (total: string) => `Итого: ₾${total}`,
    shippingIncluded: (fee: string) => `(включая доставку — ₾${fee})`,
    shippingIncludedFree: '(включая бесплатную доставку)',
    discountApplied: (code: string, amount: string) => `(скидка ${code} −₾${amount})`,
    pickupAddressLabel: 'Адрес самовывоза',
    continueShopping: 'Продолжить покупки',
    emptyHeading: 'Нечего оформлять',
    viewProducts: 'Смотреть товары →',
    backToCart: 'Вернуться в корзину',
    pageHeading: 'Оформление заказа',
    personalInfo: 'Личная информация',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Эл. почта',
    phone: 'Телефон',
    firstNamePlaceholder: 'Георгий',
    lastNamePlaceholder: 'Иванов',
    emailPlaceholder: 'example@mail.com',
    phonePlaceholder: '+995 555 123 456',
    deliveryMethod: 'Способ доставки',
    delivery: 'Доставка',
    pickup: 'Самовывоз',
    pickupAddressSection: 'Адрес самовывоза',
    deliveryAddressSection: 'Адрес доставки',
    address: 'Адрес',
    addressPlaceholder: 'Улица, город',
    shippingZone: 'Зона доставки',
    free: 'Бесплатно',
    freeShippingNudge2: (amount: string) => `Добавьте ещё ₾${amount} для бесплатной доставки.`,
    paymentMethodSection: 'Способ оплаты',
    noPaymentMethodsAvailable: 'В данный момент способы оплаты недоступны.',
    orderNotes: 'Комментарий к заказу',
    notesPlaceholder: 'напр. код домофона, удобное время доставки...',
    tosPrefix: 'Я согласен с',
    minOrderNotMet: (min: string, remaining: string) => `Минимальная сумма заказа — ₾${min}. Добавьте ещё ₾${remaining}.`,
    genericError: 'Произошла ошибка. Попробуйте снова.',
    submitPending: 'Оформление заказа...',
    submitIdle: 'Оформить заказ',
    orderSummarySidebar: 'Итоги заказа',
    bundleTag: '(набор)',
    subtotal: 'Промежуточный итог',
    shipping: 'Доставка',
    discountRow: (code: string) => `Скидка (${code})`,
    removeDiscount: 'Удалить',
    discountCodePlaceholder: 'Промокод',
    applyPending: '...',
    apply: 'Применить',
    grandTotal: 'Итого',
    hideMap: 'Скрыть карту',
    pickOnMap: 'Выбрать местоположение на карте',
    locating: 'Определяем местоположение...',
    useMyLocation: 'Использовать моё местоположение',
    searchingAddress: 'Поиск адреса...',
    locationSelected: (lat: string, lng: string) => `Местоположение выбрано (${lat}, ${lng})`,
  },
  checkoutConfirmation: {
    loading: 'Загрузка...',
    orderNotFound: 'Заказ не найден',
    backToHome: 'Вернуться на главную →',
    paymentFailedHeading: 'Оплата не выполнена',
    paymentFailedBody: 'Не удалось списать средства с вашей карты. Попробуйте снова или выберите другой способ оплаты.',
    backToCart: 'Вернуться в корзину',
    confirmingHeading: 'Подтверждение оплаты...',
    confirmingBody: 'Пожалуйста, подождите, мы подтверждаем вашу оплату.',
  },
  bundles: {
    loading: 'Загрузка...',
    emptyHeading: 'Наборов пока нет',
    pageHeading: 'Наборы',
    noImage: 'Нет изображения',
    savings: (amount: string) => `Экономия ₾${amount}`,
    addPending: '...',
    addToCart: 'Добавить в корзину',
  },
  contactForm: {
    errorName: 'Укажите имя.',
    errorMessage: 'Укажите сообщение.',
    errorContact: 'Укажите эл. почту или номер телефона.',
    errorEmail: 'Неверный формат эл. почты.',
    success: 'Спасибо! Ваше сообщение отправлено.',
    sendAnother: 'Отправить ещё одно сообщение',
    namePlaceholder: 'Имя',
    phonePlaceholder: 'Номер телефона',
    emailPlaceholder: 'Эл. почта',
    emailHelper: 'Укажите эл. почту или номер телефона',
    messagePlaceholder: 'Сообщение',
    submitError: 'Произошла ошибка. Попробуйте снова.',
    submitPending: 'Отправка...',
    submitIdle: 'Отправить',
  },
  contactPage: {
    email: 'Эл. почта',
    phone: 'Телефон',
    address: 'Адрес',
    emptyState: 'Контактная информация скоро появится.',
    backToStore: '← Вернуться в магазин',
  },
  breadcrumbs: {
    backAriaLabel: 'Назад',
  },
  pagination: {
    previous: 'Назад',
    next: 'Далее',
  },
  quickAdd: {
    ariaLabel: 'Быстро добавить в корзину',
    title: 'Добавить в корзину',
    pending: 'Добавление...',
    added: 'Добавлено',
    idle: 'Добавить в корзину',
  },
  storeHours: {
    closedToday: 'Сегодня закрыто',
    openUntil: (time: string) => `Открыто — закрывается в ${time}`,
    opensAt: (time: string) => `Откроется в ${time}`,
  },
  sizeGuide: {
    heading: 'Таблица размеров',
    closeAriaLabel: 'Закрыть',
  },
  announcementBar: {
    closeAriaLabel: 'Закрыть',
  },
  saleCountdown: {
    defaultLabel: '🔥 Акция заканчивается через',
    dayAbbr: 'д',
    hourAbbr: 'ч',
    minuteAbbr: 'м',
  },
  storeOffline: {
    closedHeading: 'Временно закрыто',
    comingSoonHeading: 'Скоро открытие',
    reopenDate: (date: string) => `Ожидаем: ${date}`,
    dateLocale: 'ru-RU',
  },
  faq: {
    headingDefault: 'Часто задаваемые вопросы',
  },
  seo: {
    productsPageTitle: 'Все товары',
    productsPageDescription: (storeName: string) => `Смотрите все товары магазина ${storeName}.`,
    categoryDescription: (categoryName: string, storeName: string) => `Смотрите товары категории ${categoryName} в магазине ${storeName}.`,
    collectionDescription: (collectionName: string, storeName: string) => `Смотрите коллекцию ${collectionName} в магазине ${storeName}.`,
    productDescriptionFallback: (productName: string, storeName: string) => `Купите ${productName} в магазине ${storeName}.`,
    contactDescriptionWithInfo: (storeName: string, info: string) => `Свяжитесь с ${storeName} — ${info}.`,
    contactDescriptionFallback: (storeName: string) => `Контактная информация ${storeName}.`,
  },
}
