import type { StorefrontStrings } from './storefront-ka'

export const en: StorefrontStrings = {
  header: {
    allProducts: 'All Products',
    categories: 'Categories',
    cart: 'Cart',
    menuAriaLabel: 'Menu',
    closeAriaLabel: 'Close',
    searchAriaLabel: 'Search',
  },
  footer: {
    poweredBy: 'Powered by NipNip',
  },
  home: {
    heroPrimaryCta: 'Shop all products',
    heroSecondaryCta: 'Learn more',
    allProductsHeading: 'All Products',
    viewAll: 'View all →',
    noProductsYet: 'No products yet.',
    slideAriaLabel: (n: number) => `Slide ${n}`,
    scrollLeftAriaLabel: 'Scroll left',
    scrollRightAriaLabel: 'Scroll right',
    emptyRowMessage: 'Nothing added yet.',
  },
  product: {
    noImage: 'No image',
    lowStock: (n: number) => `Only ${n} left!`,
    inStock: (n: number) => `In stock: ${n}`,
    outOfStock: 'Out of stock',
    addedToCart: '✓ Added to cart',
    chooseVariant: 'Choose a variant',
    addToCart: 'Add to cart',
    addToCartError: 'Something went wrong. Please try again.',
    description: 'Description',
    video: 'Video',
    relatedProducts: 'Related products',
    sizeGuide: 'Size guide',
    zoomAriaLabel: 'Zoom image',
    breadcrumbHome: 'Home',
    breadcrumbAllProducts: 'All Products',
    saleBadge: 'Sale',
  },
  grid: {
    collectionEyebrow: 'Collection',
    allProductsTitle: 'All Products',
    allCategoriesLink: 'All',
    unitProduct: 'products',
    searchPlaceholder: 'Search...',
    noProductsFound: 'No products found.',
    priceLabel: 'Price',
    minPriceAriaLabel: 'Minimum price slider',
    maxPriceAriaLabel: 'Maximum price slider',
    sortFeatured: 'Featured',
    sortPriceAsc: 'Price: low to high',
    sortPriceDesc: 'Price: high to low',
    sortNameAsc: 'Name: A-Z',
    sortNameDesc: 'Name: Z-A',
  },
  cart: {
    loading: 'Loading...',
    emptyHeading: 'Your cart is empty',
    emptySubtext: 'Browse the collection and pick something you like.',
    continueShopping: 'Continue shopping',
    heading: 'Your cart',
    itemCount: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
    bundleTag: '(bundle)',
    removeBundleAriaLabel: 'Remove bundle',
    removeItemAriaLabel: 'Remove item',
    outOfStock: 'Out of stock',
    onlyXInStock: (stock: number) => `Only ${stock} left in stock`,
    continueShoppingBack: '← Continue shopping',
    orderSummary: 'Order summary',
    total: 'Total',
    freeShippingNudge: (amount: string) => `Add ₾${amount} more for free shipping`,
    checkoutCta: 'Go to checkout',
    reduceQuantityMessage: 'Reduce the quantity to what’s in stock to continue.',
    noImage: 'No image',
    addedToast: 'Added to cart',
    bundleAddedToast: 'Bundle added to cart',
  },
  checkout: {
    paymentMethods: {
      cashOnDelivery: 'Cash on delivery',
      bankTransfer: 'Bank transfer',
      flitt: 'Pay by card',
      tbc: 'Pay by card (TBC)',
      bog: 'Pay by card (Bank of Georgia)',
      cityPay: 'Pay with crypto',
    },
    discountErrors: {
      notFound: 'This code is invalid.',
      inactive: 'This code is no longer active.',
      expired: 'This code has expired.',
      maxUses: 'This code is no longer available.',
    },
    minOrderDiscountError: (amount: string) => `Minimum order to use this code: ₾${amount}`,
    redirecting: 'Redirecting to secure checkout...',
    thankYouHeading: 'Order placed!',
    thankYouMessage: (name: string, orderId: string, email: string) =>
      `Thank you, ${name}. Your order #${orderId} has been received. Details were sent to ${email}.`,
    orderTotal: (total: string) => `Total: ₾${total}`,
    shippingIncluded: (fee: string) => `(includes shipping — ₾${fee})`,
    shippingIncludedFree: '(includes free shipping)',
    discountApplied: (code: string, amount: string) => `(discount ${code} −₾${amount})`,
    pickupAddressLabel: 'Pickup address',
    continueShopping: 'Continue shopping',
    emptyHeading: 'Nothing to check out',
    viewProducts: 'View products →',
    backToCart: 'Back to cart',
    pageHeading: 'Checkout',
    personalInfo: 'Personal information',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    firstNamePlaceholder: 'John',
    lastNamePlaceholder: 'Smith',
    emailPlaceholder: 'john@example.com',
    phonePlaceholder: '+995 555 123 456',
    deliveryMethod: 'Delivery method',
    delivery: 'Delivery',
    pickup: 'Pickup',
    pickupAddressSection: 'Pickup address',
    deliveryAddressSection: 'Delivery address',
    address: 'Address',
    addressPlaceholder: 'Street, city',
    shippingZone: 'Delivery area',
    free: 'Free',
    freeShippingNudge2: (amount: string) => `Add ₾${amount} more for free shipping.`,
    paymentMethodSection: 'Payment method',
    noPaymentMethodsAvailable: 'No payment methods are currently available.',
    orderNotes: 'Order note',
    notesPlaceholder: 'e.g. gate code, convenient delivery time...',
    tosPrefix: 'I agree to the',
    minOrderNotMet: (min: string, remaining: string) => `The minimum order is ₾${min} — add ₾${remaining} more.`,
    genericError: 'Something went wrong. Please try again.',
    submitPending: 'Placing order...',
    submitIdle: 'Place order',
    orderSummarySidebar: 'Order summary',
    bundleTag: '(bundle)',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    discountRow: (code: string) => `Discount (${code})`,
    removeDiscount: 'Remove',
    discountCodePlaceholder: 'Discount code',
    applyPending: '...',
    apply: 'Apply',
    grandTotal: 'Total',
    hideMap: 'Hide map',
    pickOnMap: 'Choose location on map',
    locating: 'Finding your location...',
    useMyLocation: 'Use my location',
    searchingAddress: 'Looking up address...',
    locationSelected: (lat: string, lng: string) => `Location selected (${lat}, ${lng})`,
  },
  checkoutConfirmation: {
    loading: 'Loading...',
    orderNotFound: 'Order not found',
    backToHome: 'Back to home →',
    paymentFailedHeading: 'Payment failed',
    paymentFailedBody: 'We couldn’t charge your card. Please try again or choose a different payment method.',
    backToCart: 'Back to cart',
    confirmingHeading: 'Confirming payment...',
    confirmingBody: 'Please wait while we confirm your payment.',
  },
  bundles: {
    loading: 'Loading...',
    emptyHeading: 'No bundles yet',
    pageHeading: 'Bundles',
    noImage: 'No image',
    savings: (amount: string) => `Save ₾${amount}`,
    addPending: '...',
    addToCart: 'Add to cart',
  },
  contactForm: {
    errorName: 'Name is required.',
    errorMessage: 'Message is required.',
    errorContact: 'Provide an email or a phone number.',
    errorEmail: 'Email format is invalid.',
    success: 'Thanks! Your message has been sent.',
    sendAnother: 'Send another message',
    namePlaceholder: 'Name',
    phonePlaceholder: 'Phone number',
    emailPlaceholder: 'Email',
    emailHelper: 'Provide an email or a phone number',
    messagePlaceholder: 'Message',
    submitError: 'Something went wrong. Please try again.',
    submitPending: 'Sending...',
    submitIdle: 'Send',
  },
  contactPage: {
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    emptyState: 'Contact information will be added soon.',
    backToStore: '← Back to store',
  },
  breadcrumbs: {
    backAriaLabel: 'Go back',
  },
  pagination: {
    previous: 'Previous',
    next: 'Next',
  },
  quickAdd: {
    ariaLabel: 'Quick add to cart',
    title: 'Add to cart',
    pending: 'Adding...',
    added: 'Added',
    idle: 'Add to cart',
  },
  storeHours: {
    closedToday: 'Closed today',
    openUntil: (time: string) => `Open — closes at ${time}`,
    opensAt: (time: string) => `Opens at ${time}`,
  },
  sizeGuide: {
    heading: 'Size guide',
    closeAriaLabel: 'Close',
  },
  announcementBar: {
    closeAriaLabel: 'Close',
  },
  saleCountdown: {
    defaultLabel: '🔥 Sale ends in',
    dayAbbr: 'd',
    hourAbbr: 'h',
    minuteAbbr: 'm',
  },
  storeOffline: {
    closedHeading: 'Temporarily closed',
    comingSoonHeading: 'Opening soon',
    reopenDate: (date: string) => `We'll be back: ${date}`,
    dateLocale: 'en-US',
  },
  faq: {
    headingDefault: 'Frequently Asked Questions',
  },
  seo: {
    productsPageTitle: 'All Products',
    productsPageDescription: (storeName: string) => `Browse all products from ${storeName}.`,
    categoryDescription: (categoryName: string, storeName: string) => `Browse ${categoryName} products from ${storeName}.`,
    collectionDescription: (collectionName: string, storeName: string) => `Browse the ${collectionName} collection from ${storeName}.`,
    productDescriptionFallback: (productName: string, storeName: string) => `Shop ${productName} at ${storeName}.`,
    contactDescriptionWithInfo: (storeName: string, info: string) => `Get in touch with ${storeName} — ${info}.`,
    contactDescriptionFallback: (storeName: string) => `Contact information for ${storeName}.`,
  },
}
