// Fixed UI chrome for the customer-facing storefront (buttons, labels, headings, empty states,
// form labels, validation/error messages, SEO templates). Merchant-entered content (product
// names/descriptions, page text, category/collection names, FAQ content) is NOT covered here —
// it's rendered exactly as the merchant typed it, in whatever language, regardless of the
// storefront language the shopper picks.
export const ka = {
  header: {
    allProducts: 'ყველა პროდუქტი',
    categories: 'კატეგორიები',
    cart: 'კალათა',
    menuAriaLabel: 'მენიუ',
    closeAriaLabel: 'დახურვა',
    searchAriaLabel: 'ძიება',
  },
  footer: {
    poweredBy: 'შექმნილია NipNip-ის მიერ',
  },
  home: {
    heroPrimaryCta: 'ყველა პროდუქტის ნახვა',
    heroSecondaryCta: 'მეტის ნახვა',
    allProductsHeading: 'ყველა პროდუქტი',
    viewAll: 'ყველას ნახვა →',
    noProductsYet: 'პროდუქტები ჯერ არ არის.',
    slideAriaLabel: (n: number) => `სლაიდი ${n}`,
    scrollLeftAriaLabel: 'გადახვევა მარცხნივ',
    scrollRightAriaLabel: 'გადახვევა მარჯვნივ',
    emptyRowMessage: 'ჯერ არაფერია დამატებული.',
  },
  product: {
    noImage: 'სურათი არ არის',
    lowStock: (n: number) => `მხოლოდ ${n} ცალია დარჩენილი!`,
    inStock: (n: number) => `მარაგშია: ${n} ცალი`,
    outOfStock: 'არ არის მარაგში',
    addedToCart: '✓ დაემატა კალათაში',
    chooseVariant: 'აირჩიეთ ვარიანტი',
    addToCart: 'კალათაში დამატება',
    addToCartError: 'დაფიქსირდა შეცდომა. სცადეთ თავიდან.',
    description: 'აღწერა',
    video: 'ვიდეო',
    relatedProducts: 'მსგავსი პროდუქტები',
    sizeGuide: 'საზომი ცხრილი',
    zoomAriaLabel: 'სურათის გადიდება',
    breadcrumbHome: 'მთავარი',
    breadcrumbAllProducts: 'ყველა პროდუქტი',
    saleBadge: 'ფასდაკლება',
  },
  grid: {
    collectionEyebrow: 'კოლექცია',
    allProductsTitle: 'ყველა პროდუქტი',
    allCategoriesLink: 'ყველა',
    unitProduct: 'პროდუქტი',
    searchPlaceholder: 'ძიება...',
    noProductsFound: 'პროდუქტი ვერ მოიძებნა.',
    priceLabel: 'ფასი',
    minPriceAriaLabel: 'მინიმალური ფასის სლაიდერი',
    maxPriceAriaLabel: 'მაქსიმალური ფასის სლაიდერი',
    sortFeatured: 'რეკომენდებული',
    sortPriceAsc: 'ფასი: დაბლიდან მაღლა',
    sortPriceDesc: 'ფასი: მაღლიდან დაბლა',
    sortNameAsc: 'სახელი: ა-ჰ',
    sortNameDesc: 'სახელი: ჰ-ა',
  },
  cart: {
    loading: 'იტვირთება...',
    emptyHeading: 'თქვენი კალათა ცარიელია',
    emptySubtext: 'დაათვალიერეთ კოლექცია და აირჩიეთ სასურველი პროდუქტი.',
    continueShopping: 'შოპინგის გაგრძელება',
    heading: 'თქვენი კალათა',
    itemCount: (n: number) => `${n} ნივთი`,
    bundleTag: '(ბანდლი)',
    removeBundleAriaLabel: 'ბანდლის წაშლა',
    removeItemAriaLabel: 'ნივთის წაშლა',
    outOfStock: 'არ არის მარაგში',
    onlyXInStock: (stock: number) => `მხოლოდ ${stock} ცალია მარაგში`,
    continueShoppingBack: '← შოპინგის გაგრძელება',
    orderSummary: 'შეკვეთის შეჯამება',
    total: 'სულ',
    freeShippingNudge: (amount: string) => `დაამატეთ კიდევ ₾${amount} და მიწოდება იქნება უფასო`,
    checkoutCta: 'გადახდაზე გადასვლა',
    reduceQuantityMessage: 'შეამცირეთ რაოდენობა მარაგში არსებულამდე, რომ გააგრძელოთ.',
    noImage: 'სურათი არ არის',
    addedToast: 'პროდუქტი დაემატა კალათაში',
    bundleAddedToast: 'ბანდლი დაემატა კალათაში',
  },
  checkout: {
    paymentMethods: {
      cashOnDelivery: 'გადახდა მიტანისას',
      bankTransfer: 'საბანკო გადარიცხვა',
      flitt: 'ბარათით გადახდა',
      tbc: 'ბარათით გადახდა (TBC)',
      bog: 'ბარათით გადახდა (საქართველოს ბანკი)',
      cityPay: 'გადახდა კრიპტოვალუტით',
    },
    discountErrors: {
      notFound: 'კოდი არასწორია.',
      inactive: 'კოდი აღარ არის აქტიური.',
      expired: 'კოდის ვადა ამოიწურა.',
      maxUses: 'კოდი აღარ არის ხელმისაწვდომი.',
    },
    minOrderDiscountError: (amount: string) => `მინიმალური შეკვეთა კოდის გამოსაყენებლად: ₾${amount}`,
    redirecting: 'გადამისამართება უსაფრთხო გადახდის გვერდზე...',
    thankYouHeading: 'შეკვეთა გაფორმდა!',
    thankYouMessage: (name: string, orderId: string, email: string) =>
      `გმადლობთ, ${name}. თქვენი შეკვეთა #${orderId} მიღებულია. დეტალები გამოგზავნილია ${email}-ზე.`,
    orderTotal: (total: string) => `სულ: ₾${total}`,
    shippingIncluded: (fee: string) => `(მათ შორის მიწოდება — ₾${fee})`,
    shippingIncludedFree: '(მათ შორის მიწოდება — უფასო)',
    discountApplied: (code: string, amount: string) => `(ფასდაკლება ${code} −₾${amount})`,
    pickupAddressLabel: 'თვითგატანის მისამართი',
    continueShopping: 'შოპინგის გაგრძელება',
    emptyHeading: 'გადასახდელი ნივთები არ არის',
    viewProducts: 'პროდუქტების ნახვა →',
    backToCart: 'კალათაში დაბრუნება',
    pageHeading: 'გადახდა',
    personalInfo: 'პირადი ინფორმაცია',
    firstName: 'სახელი',
    lastName: 'გვარი',
    email: 'ელფოსტა',
    phone: 'ტელეფონი',
    firstNamePlaceholder: 'გიორგი',
    lastNamePlaceholder: 'გიორგაძე',
    emailPlaceholder: 'giorgi@example.com',
    phonePlaceholder: '+995 555 123 456',
    deliveryMethod: 'მიწოდების მეთოდი',
    delivery: 'მიწოდება',
    pickup: 'თვითგატანა',
    pickupAddressSection: 'თვითგატანის მისამართი',
    deliveryAddressSection: 'მიწოდების მისამართი',
    address: 'მისამართი',
    addressPlaceholder: 'ქუჩა, ქალაქი',
    shippingZone: 'მიწოდების არეალი',
    free: 'უფასო',
    freeShippingNudge2: (amount: string) => `დაამატეთ კიდევ ₾${amount} და მიწოდება იქნება უფასო.`,
    paymentMethodSection: 'გადახდის მეთოდი',
    noPaymentMethodsAvailable: 'ამჟამად გადახდის მეთოდი მიუწვდომელია.',
    orderNotes: 'შენიშვნა შეკვეთაზე',
    notesPlaceholder: 'მაგ. კარიბჭის კოდი, მიწოდების მოსახერხებელი დრო...',
    tosPrefix: 'ვეთანხმები',
    minOrderNotMet: (min: string, remaining: string) => `მინიმალური შეკვეთის ოდენობაა ₾${min} — დაამატეთ კიდევ ₾${remaining}.`,
    genericError: 'დაფიქსირდა შეცდომა. სცადეთ თავიდან.',
    submitPending: 'შეკვეთის გაფორმება...',
    submitIdle: 'შეკვეთის გაფორმება',
    orderSummarySidebar: 'შეკვეთის შეჯამება',
    bundleTag: '(ბანდლი)',
    subtotal: 'ჯამი',
    shipping: 'მიწოდება',
    discountRow: (code: string) => `ფასდაკლება (${code})`,
    removeDiscount: 'წაშლა',
    discountCodePlaceholder: 'ფასდაკლების კოდი',
    applyPending: '...',
    apply: 'გააქტიურება',
    grandTotal: 'სულ',
    hideMap: 'რუკის დამალვა',
    pickOnMap: 'მდებარეობის არჩევა რუკაზე',
    locating: 'ეძებს მდებარეობას...',
    useMyLocation: 'ჩემი მდებარეობის გამოყენება',
    searchingAddress: 'მისამართის ძებნა...',
    locationSelected: (lat: string, lng: string) => `მდებარეობა შერჩეულია (${lat}, ${lng})`,
  },
  checkoutConfirmation: {
    loading: 'იტვირთება...',
    orderNotFound: 'შეკვეთა ვერ მოიძებნა',
    backToHome: 'მთავარ გვერდზე დაბრუნება →',
    paymentFailedHeading: 'გადახდა ვერ შესრულდა',
    paymentFailedBody: 'თქვენი ბარათიდან თანხის ჩამოჭრა ვერ მოხერხდა. სცადეთ თავიდან ან აირჩიეთ სხვა გადახდის მეთოდი.',
    backToCart: 'კალათაში დაბრუნება',
    confirmingHeading: 'გადახდის დადასტურება...',
    confirmingBody: 'გთხოვთ დაელოდოთ, ვადასტურებთ თქვენს გადახდას.',
  },
  bundles: {
    loading: 'იტვირთება...',
    emptyHeading: 'ბანდლები არ არის',
    pageHeading: 'ბანდლები',
    noImage: 'სურათი არ არის',
    savings: (amount: string) => `დაზოგე ₾${amount}`,
    addPending: '...',
    addToCart: 'კალათაში დამატება',
  },
  contactForm: {
    errorName: 'სახელი სავალდებულოა.',
    errorMessage: 'შეტყობინება სავალდებულოა.',
    errorContact: 'მიუთითეთ ელფოსტა ან ტელეფონის ნომერი.',
    errorEmail: 'ელფოსტის ფორმატი არასწორია.',
    success: 'მადლობთ! თქვენი შეტყობინება გაიგზავნა.',
    sendAnother: 'ახალი შეტყობინების გაგზავნა',
    namePlaceholder: 'სახელი',
    phonePlaceholder: 'ტელეფონის ნომერი',
    emailPlaceholder: 'ელფოსტა',
    emailHelper: 'მიუთითეთ ელფოსტა ან ტელეფონის ნომერი',
    messagePlaceholder: 'შეტყობინება',
    submitError: 'დაფიქსირდა შეცდომა. სცადეთ თავიდან.',
    submitPending: 'იგზავნება...',
    submitIdle: 'გაგზავნა',
  },
  contactPage: {
    email: 'ელფოსტა',
    phone: 'ტელეფონი',
    address: 'მისამართი',
    emptyState: 'საკონტაქტო ინფორმაცია მალე დაემატება.',
    backToStore: '← მაღაზიაში დაბრუნება',
    formHeading: 'დაგვიტოვე წერილი',
  },
  breadcrumbs: {
    backAriaLabel: 'უკან დაბრუნება',
  },
  pagination: {
    previous: 'წინა',
    next: 'შემდეგი',
  },
  quickAdd: {
    ariaLabel: 'სწრაფად კალათაში დამატება',
    title: 'კალათაში დამატება',
    pending: 'დამატება...',
    added: 'დამატებულია',
    idle: 'კალათაში დამატება',
  },
  storeHours: {
    closedToday: 'დღეს დაკეტილია',
    openUntil: (time: string) => `ღიაა — იხურება ${time}-ზე`,
    opensAt: (time: string) => `იხსნება ${time}-ზე`,
  },
  sizeGuide: {
    heading: 'საზომი ცხრილი',
    closeAriaLabel: 'დახურვა',
  },
  announcementBar: {
    closeAriaLabel: 'დახურვა',
  },
  saleCountdown: {
    defaultLabel: '🔥 ფასდაკლება მთავრდება:',
    dayAbbr: 'დ',
    hourAbbr: 'სთ',
    minuteAbbr: 'წთ',
  },
  storeOffline: {
    closedHeading: 'დროებით დაკეტილია',
    comingSoonHeading: 'მალე გაიხსნება',
    reopenDate: (date: string) => `ველოდებით: ${date}`,
    dateLocale: 'ka-GE',
  },
  faq: {
    headingDefault: 'ხშირად დასმული კითხვები',
  },
  seo: {
    productsPageTitle: 'ყველა პროდუქტი',
    productsPageDescription: (storeName: string) => `დაათვალიერეთ ${storeName}-ის ყველა პროდუქტი.`,
    categoryDescription: (categoryName: string, storeName: string) => `დაათვალიერეთ ${categoryName} კატეგორიის პროდუქტები ${storeName}-ში.`,
    collectionDescription: (collectionName: string, storeName: string) => `დაათვალიერეთ ${collectionName} კოლექციის პროდუქტები ${storeName}-ში.`,
    productDescriptionFallback: (productName: string, storeName: string) => `შეიძინეთ ${productName} მაღაზიაში ${storeName}.`,
    contactDescriptionWithInfo: (storeName: string, info: string) => `დაუკავშირდით ${storeName}-ს — ${info}.`,
    contactDescriptionFallback: (storeName: string) => `${storeName}-ის საკონტაქტო ინფორმაცია.`,
  },
} as const

type DeepStorefrontStringify<T> = {
  [K in keyof T]: T[K] extends (...args: never[]) => string
    ? T[K]
    : T[K] extends object
    ? DeepStorefrontStringify<T[K]>
    : string
}

export type StorefrontStrings = DeepStorefrontStringify<typeof ka>
